INSERT INTO post_office_t VALUES('Bhimpore', 396210, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Daman', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Dabhel', 396215, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Daman I.E.', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Daman I.E.', 396215, 'Daman ', 'Daman and Diu', 'Sub Office(Delivery)', '', 'Valsad', 'Daman Taluk of Daman District', '0260-2244001');
INSERT INTO post_office_t VALUES('Daman', 396210, 'Daman ', 'Daman and Diu', 'Sub Office(Delivery)', '', 'Valsad', 'Daman Taluk of Daman District', '0260-2254353');
INSERT INTO post_office_t VALUES('Dholar', 396220, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Moti Daman', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Dunetha', 396210, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Daman', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Kachigam', 396215, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Daman I.E.', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Kadaiya', 396210, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Daman', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Kunta', 396215, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Daman I.E.', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Magarwada', 396220, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Moti Daman', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Marvad', 396210, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Daman', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Moti Daman', 396220, 'Daman ', 'Daman and Diu', 'Sub Office(Delivery)', '', 'Valsad', 'Daman Taluk of Daman District', '0260-2230453');
INSERT INTO post_office_t VALUES('Nani Vankad', 396210, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Daman', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Varkund', 396210, 'Daman ', 'Daman and Diu', 'Branch Office(Delivery)', 'Daman', 'Valsad', 'Daman Taluk of Daman District', '');
INSERT INTO post_office_t VALUES('Bucharvada', 362570, 'Diu ', 'Daman and Diu', 'Branch Office(Delivery)', 'Wanakbara', 'Junagadh', 'Diu Taluk of Diu District', '');
INSERT INTO post_office_t VALUES('Diu', 362520, 'Diu ', 'Daman and Diu', 'Sub Office(Delivery)', '', 'Junagadh', 'Diu Taluk of Diu District', '02875-253200');
INSERT INTO post_office_t VALUES('Diu Zampa', 362520, 'Diu ', 'Daman and Diu', 'Sub Office(Non Delivery)', '', 'Junagadh', 'Diu Taluk of Diu District', '02875-252167');
INSERT INTO post_office_t VALUES('Fudam', 362520, 'Diu ', 'Daman and Diu', 'Branch Office(Delivery)', 'Diu', 'Junagadh', 'Diu Taluk of Diu District', '');
INSERT INTO post_office_t VALUES('Ghoghla', 362540, 'Diu ', 'Daman and Diu', 'Sub Office(Delivery)', '', 'Junagadh', 'Diu U.T. Taluk of Diu District', '02875-252127');
INSERT INTO post_office_t VALUES('Wanakbara', 362570, 'Diu ', 'Daman and Diu', 'Sub Office(Delivery)', '', 'Junagadh', 'Taluk of Diu District', '02876-220311');
