INSERT INTO post_office_t VALUES('Akkaraivattam', 609604, 'Branch Office(Delivery)', 'Neravy', 'Nagapattinam', 'Neravy Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Ambagarathur', 609601, 'Sub Office(Delivery)', '', 'Nagapattinam', 'Karaikal Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04368-251534');
INSERT INTO post_office_t VALUES('Dharmapuram', 609602, 'Branch Office(Delivery)', 'Karaikal South', 'Nagapattinam', 'Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Karaikal Bazaar', 609602, 'Sub Office(Non Delivery)', '', 'Nagapattinam', 'Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04365-242055');
INSERT INTO post_office_t VALUES('Karaikal', 609602, 'Sub Office(Delivery)', '', 'Nagapattinam', 'Karaikal Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04368-222419');
INSERT INTO post_office_t VALUES('Karaikal South', 609602, 'Sub Office(Non Delivery)', '', 'Nagapattinam', 'Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04365-242055');
INSERT INTO post_office_t VALUES('Karaikalmedu', 609605, 'Branch Office(Non Delivery)', 'Thalatheru', 'Nagapattinam', 'Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Karaikoilpathu', 609605, 'Branch Office(Non Delivery)', 'Thalatheru', 'Nagapattinam', 'Karaikal Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Karukkangudi', 609607, 'Branch Office(Delivery)', 'Tirunallar', 'Nagapattinam', 'Thirunallar Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Kottuchery', 609609, 'Sub Office(Delivery)', '', 'Nagapattinam', 'Kottucherry Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04365-242055');
INSERT INTO post_office_t VALUES('Kurumbagaram', 609603, 'Branch Office(Delivery)', 'Nedungadu', 'Nagapattinam', 'Nedungadu Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Madagadi', 609602, 'Branch Office(Non Delivery)', 'Karaikal South', 'Nagapattinam', 'Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Melakasakudi', 609603, 'Branch Office(Delivery)', 'Nedungadu', 'Nagapattinam', 'Nedungadu Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Nallambal', 609601, 'Branch Office(Delivery)', 'Ambagarathur', 'Nagapattinam', 'Thirunallar Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Nallathur', 609603, 'Branch Office(Delivery)', 'Nedungadu', 'Nagapattinam', 'Nedungadu Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Nedungadu', 609603, 'Sub Office(Delivery)', '', 'Nagapattinam', 'Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04368-291071');
INSERT INTO post_office_t VALUES('Neravy', 609602, 'Sub Office(Delivery)', '', 'Nagapattinam', 'Neravy Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04368-238206');
INSERT INTO post_office_t VALUES('Seithur', 609601, 'Branch Office(Delivery)', 'Ambagarathur', 'Nagapattinam', 'Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Sellur', 609607, 'Branch Office(Delivery)', 'Tirunallar', 'Nagapattinam', 'Thirunallar Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Surakudi', 609607, 'Branch Office(Delivery)', 'Tirunallar', 'Nagapattinam', 'Thirunallar Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('T.R.Pattinam South', 609606, 'Branch Office(Non Delivery)', 'Tirumalairayanpattinam', 'Nagapattinam', 'Thirumalairayan Pattinam Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Thalatheru', 609605, 'Sub Office(Delivery)', '', 'Nagapattinam', 'Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04365-230300');
INSERT INTO post_office_t VALUES('Tirumalairayanpattinam', 609606, 'Sub Office(Delivery)', '', 'Nagapattinam', 'Karaikal Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04368-234493');
INSERT INTO post_office_t VALUES('Tirunallar', 609607, 'Sub Office(Delivery)', '', 'Nagapattinam', 'Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '04368-236505');
INSERT INTO post_office_t VALUES('Tiruvettakudi', 609609, 'Branch Office(Delivery)', 'Kottuchery', 'Nagapattinam', 'Kottucherry Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Varichikudi', 609609, 'Branch Office(Delivery)', 'Kottuchery', 'Nagapattinam', 'Kottucherry Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Vizhithiyur', 609607, 'Branch Office(Delivery)', 'Tirunallar', 'Nagapattinam', 'Neravy Commune Panchayat Taluk of Karaikal District', 'Karaikal ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Naluthara', 673310, 'Branch Office(Delivery)', 'Mahe', 'Vadakara', 'Mahe Ut Taluk of Mahe District', 'Mahe ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Pallur', 673310, 'Branch Office(Delivery)', 'Mahe', 'Vadakara', 'Mahe Ut Taluk of Mahe District', 'Mahe ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Mahe', 673310, 'Sub Office(Delivery)', '', 'Vadakara', 'Vadakara Taluk of Kozhikode District', 'Kozhikode ', 'Puducherry', '0490-2332230');
INSERT INTO post_office_t VALUES('Abishegapakkam', 605007, 'Branch Office(Delivery)', 'Ariyankuppam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Ariyankuppam', 605007, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2600105');
INSERT INTO post_office_t VALUES('Arumbarthapuram', 605110, 'Branch Office(Delivery)', 'Villiyanur', 'Pondicherry', 'Villianur Commune Panchayat Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Bahoor', 607402, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2633680');
INSERT INTO post_office_t VALUES('Bommayarpalayam', 605104, 'Branch Office(Delivery)', 'Kottakuppam', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Calapet', 605014, 'Branch Office(Non Delivery)', 'Ariyankuppam', 'Pondicherry University', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Courivinatham', 607402, 'Branch Office(Delivery)', 'Bahoor', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Dhanvantry Nagar', 605006, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2275453');
INSERT INTO post_office_t VALUES('Embalam', 605106, 'Branch Office(Delivery)', 'Nettapakkam', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Irumbai', 605111, 'Branch Office(Non Delivery)', 'Tiruchitambalam', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Karayamputhur', 605106, 'Branch Office(Delivery)', 'Nettapakkam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Karikalambakkam', 605007, 'Branch Office(Delivery)', 'Ariyankuppam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Kariyamanikam', 605106, 'Branch Office(Delivery)', 'Nettapakkam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Kijour', 605106, 'Branch Office(Delivery)', 'Nettapakkam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Kilpudupattu', 605014, 'Branch Office(Delivery)', 'Pondicherry University', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Kirumambakkam', 607402, 'Branch Office(Delivery)', 'Bahoor', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Korkadu', 605110, 'Branch Office(Delivery)', 'Villiyanur', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Kottakuppam', 605104, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Kuilapalayam', 605101, 'Branch Office(Non Delivery)', 'Auroville', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Lawspet', 605008, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2254222');
INSERT INTO post_office_t VALUES('Maducore', 605105, 'Branch Office(Delivery)', 'Mokshakulam', 'Villupuram', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Manamedu', 607402, 'Branch Office(Delivery)', 'Bahoor', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Manapeth', 607402, 'Branch Office(Delivery)', 'Bahoor', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Mandagapet', 605106, 'Branch Office(Delivery)', 'Nettapakkam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Mangalam', 605110, 'Branch Office(Delivery)', 'Villiyanur', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Mannadipattu', 605501, 'Branch Office(Non Delivery)', 'Tirukkanur', 'Pondicherry University', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Morattandi', 605101, 'Branch Office(Delivery)', 'Auroville', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Mottoupalayam', 605009, 'Branch Office(Non Delivery)', 'Thattanchavady', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Mouroungapakkam', 605004, 'Branch Office(Non Delivery)', 'Mudaliarpet', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Pillayarkuppam', 607402, 'Branch Office(Delivery)', 'Bahoor', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Moutrepaleam', 605009, 'Branch Office(Non Delivery)', 'Thattanchavady', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Mudaliarpet', 605004, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2354422');
INSERT INTO post_office_t VALUES('Muthialpet', 605003, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2234966');
INSERT INTO post_office_t VALUES('Nallavadu', 605007, 'Branch Office(Delivery)', 'Ariyankuppam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Nellithoppe', 605005, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2204633');
INSERT INTO post_office_t VALUES('Nettapakkam', 605106, 'Sub Office(Delivery)', '', 'Pondicherry University', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2699964');
INSERT INTO post_office_t VALUES('Odiampet', 605110, 'Villiyanur Office(Delivery)', 'Villiyanur', 'Pondicherry', 'Villianur Commune Panchayat Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Ozhugarai', 605010, 'Branch Office(Non Delivery)', 'Reddiyarpalayam', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Pandakkal', 673310, 'Branch Office(Delivery)', 'Mahe', 'Vadakara', 'Ut Of Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Pondicherry', 605001, 'Head Office(Delivery)', '', '', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2336532');
INSERT INTO post_office_t VALUES('Pondicherry University', 605014, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2655155');
INSERT INTO post_office_t VALUES('Pooranankuppam', 605007, 'Branch Office(Delivery)', 'Ariyankuppam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Poothurai', 605111, 'Branch Office(Delivery)', 'Tiruchitambalam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Rayapudupakkam', 605111, 'Branch Office(Delivery)', 'Tiruchitambalam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Reddiyarpalayam', 605010, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2291044');
INSERT INTO post_office_t VALUES('Saram(Py)', 605013, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '04132-2241600');
INSERT INTO post_office_t VALUES('Sedarapet', 605111, 'Branch Office(Non Delivery)', 'Tiruchitambalam', 'Pondicherry University', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Seliamedu', 607402, 'Branch Office(Delivery)', 'Bahoor', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Sellipet', 605501, 'Branch Office(Delivery)', 'Tirukkanur', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Sri Aurobindo Ashram', 605002, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2222124');
INSERT INTO post_office_t VALUES('Sulthanpet', 605110, 'Branch Office(Delivery)', 'Villiyanur', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', 'Villianur Commune Panchayat Taluk of Pondicherry District');
INSERT INTO post_office_t VALUES('Thattanchavady', 605009, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2275350');
INSERT INTO post_office_t VALUES('Thengaithittu', 605004, 'Branch Office(Non Delivery)', 'Mudaliarpet', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '04132-2241600');
INSERT INTO post_office_t VALUES('Thimmanaickenpalayam', 605007, 'Branch Office(Delivery)', 'Ariyankuppam', 'Pondicherry', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Tirukkanur', 605501, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2680185');
INSERT INTO post_office_t VALUES('Vadhanur', 605501, 'Branch Office(Delivery)', 'Tirukkanur', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Veerampattinam', 605007, 'Branch Office(Non Delivery)', 'Ariyankuppam', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Venkata Nagar', 605011, 'Sub Office(Delivery)', '', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2211866');
INSERT INTO post_office_t VALUES('Villiyanur', 605110, 'Sub Office(Delivery)', '', 'Pondicherry', 'Villianur Commune Panchayat Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0413-2661616');
INSERT INTO post_office_t VALUES('Vimacoundinpaleam', 605009, 'Branch Office(Non Delivery)', 'Thattanchavady', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Viranam', 605106, 'Branch Office(Delivery)', 'Nettapakkam', 'Pondicherry', 'Pondichery Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '');
INSERT INTO post_office_t VALUES('Yanam', 533464, 'Sub Office(Delivery)', '', 'Kakinada', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0884-2321120');
INSERT INTO post_office_t VALUES('Yanam', 533464, 'Sub Office(Delivery)', '', 'Kakinada', 'Pondicherry Taluk of Pondicherry District', 'Pondicherry ', 'Puducherry', '0884-2321120');
