INSERT INTO bank_branch_t VALUES('Trivandrum', 'Thiruvananthapuram', 'Reserve Bank OF India, Trivandrum', '0', 'NA', 'RBIS0THPA01', 18837);
INSERT INTO bank_branch_t VALUES('Shimla', 'Shimla', 'Rural Planning AND Credit Department, B 478, Sector IV, NEW Shimla, Shimla 171009', '0', 'NA', 'RBIS0SMPA01', 18831);
INSERT INTO bank_branch_t VALUES('Raipur', 'Raipur', '54 BY 949, Subhashish Parisar, Satya Prem Vihar, Mahadev Ghat Road, Sundar Nagar, Raipur 492 013', '0', 'NA', 'RBIS0RPPA01', 18827);
INSERT INTO bank_branch_t VALUES('Ranchi', 'Ranchi', '4TH FLOOR.RRDA BUILDING.KATCHEHRI Road, Ranchi 834001. Jharkhand', '0', 'NA', 'RBIS0RNPA01', 18833);
INSERT INTO bank_branch_t VALUES('PAD Patna', 'Patna', 'PAD Patna, Patna', '0', 'NA', 'RBIS0PTPA01', 18825);
INSERT INTO bank_branch_t VALUES('Panaji', 'Panaji', 'Geras Imperium II 7TH Floor 70706 Patto Panaji GOA 403001', '0', 'NA', 'RBIS0PJPA01', 18829);
INSERT INTO bank_branch_t VALUES('CBD Belapur', 'Navi Mumbai', 'Plot NO.3, Sector 10, H.H. Nirmaladevi Marg, Cbd, Belapur, Navi Mumbai 400614', '0', 'NA', 'RBIS0NMPA01', 18841);
INSERT INTO bank_branch_t VALUES('PAD Nagpur', 'Nagpur', 'PAD Nagpur, Nagpur', '0', 'NA', 'RBIS0NGPA01', 18840);
INSERT INTO bank_branch_t VALUES('RBI PAD', 'Hyderabad', 'Rbi, Lakdikapul, Hyderabad', '0', 'NA', 'RBIS0NEFTHY', 18823);
INSERT INTO bank_branch_t VALUES('PAD NEW Delhi', 'Delhi', '6,sansad Marg, NEW Delhi 110001', '0', 'NA', 'RBIS0NDPA01', 18828);
INSERT INTO bank_branch_t VALUES('PAD Mumbai', 'Greater Bombay', 'Pad, Ground Floor, Main Building, Fort Mumbai- 400001', '0', 'NA', 'RBIS0MBPA04', 18839);
INSERT INTO bank_branch_t VALUES('RBI PAD Lucknow', 'Lucknow', 'RBI Pad, LUCKNOW.', '0', 'NA', 'RBIS0LKPA01', 18850);
INSERT INTO bank_branch_t VALUES('PAD Kanpur', 'Kanpur', 'PAD Kanpur, Kanpur', '0', 'NA', 'RBIS0KNPA01', 18849);
INSERT INTO bank_branch_t VALUES('RBI PAD Kolkata', 'Kolkata', 'RBI Pad, Kolkata', '0', 'NA', 'RBIS0KLPA01', 18852);
INSERT INTO bank_branch_t VALUES('Kochi', 'Ernakulam', 'Foreign Exchange Department, Reserve Bank OF India, Ernakulam North, Kochi 682018', '0', 'NA', 'RBIS0KCPA01', 18836);
INSERT INTO bank_branch_t VALUES('Public Accounts Dept', 'Jaipur', 'Rambagh Circle, Tonk Road, Jaipur-302004', '0', 'NA', 'RBIS0JPPA01', 18845);
INSERT INTO bank_branch_t VALUES('Jammu', 'Jammu', 'Reserve Bank OF India, Jammu', '0', 'NA', 'RBIS0JMPA01', 18832);
INSERT INTO bank_branch_t VALUES('PAD Guwahati', 'Guwahati', 'PAD Guwahati', '0', 'NA', 'RBIS0GWPA01', 18824);
INSERT INTO bank_branch_t VALUES('Dehradun', 'Dehradun', '74 BY 1, Rajpur Road, Dehradun', '0', 'NA', 'RBIS0DNPA01', 18851);
INSERT INTO bank_branch_t VALUES('Chennai Regional Office', 'Chennai', 'Pad, Chennai Main Office, Chennai', '0', 'NA', 'RBIS0CNPA01', 18847);
INSERT INTO bank_branch_t VALUES('PAD Chandigarh', 'Chandigarh', 'PAD Chandigarh, Chandigarh', '0', 'NA', 'RBIS0CGPA01', 18826);
INSERT INTO bank_branch_t VALUES('PAD Bhopal', 'Bhopal', 'PAD Bhopal, Bhopal', '0', 'NA', 'RBIS0BLPA01', 18838);
INSERT INTO bank_branch_t VALUES('Bangalore Regional Office', 'Bangalore', '10 BY 3 BY 8, Nrupthunga Road, Bangalore-560 001', '0', 'NA', 'RBIS0BGPA01', 18834);
INSERT INTO bank_branch_t VALUES('PAD Bhubaneswar', 'Khurda', 'PAD Bhubaneswar, Bhubaneswar', '0', 'NA', 'RBIS0BBPA01', 18844);
INSERT INTO bank_branch_t VALUES('Ahmedabad Regional Office', 'Ahmedabad', 'Pad, Ahmedabad Main Office, Ahmedabad', '0', 'NA', 'RBIS0AHPA01', 18830);
INSERT INTO bank_branch_t VALUES('Shillong', 'Shillong', 'Apphira Building, Fruit Garden, Shillong Jowai Road, Shillong', '2501839', 'NA', 'RBIS0SLPA01', 18843);
INSERT INTO bank_branch_t VALUES('Reserve Bank Staff College Rbsc Chennai', 'Chennai', '5,annasalai, Teynampet, Chennai', '24302700', 'NA', 'RBIS0SCPA01', 18847);
INSERT INTO bank_branch_t VALUES('Samadhan - HR Operations Unit', 'Bengaluru', 'Reserve Bank OF India, Bengaluru', '22180100', 'NA', 'RBIS0SAMADN', 18835);
INSERT INTO bank_branch_t VALUES('CAB Pune', 'Pune', 'Ganesh Khind Road, Near Esquare', '0', 'NA', 'RBIS0PUPA01', 18842);
INSERT INTO bank_branch_t VALUES('Gangtok', 'Gangtok', 'Lrsyzaltk', '281117', 'NA', 'RBIS0GTPA01', 18846);
INSERT INTO bank_branch_t VALUES('RBI Neft Rtgs GST Collection', 'Mumbai', 'ASST. General Manager, GST Cell, Reserve Bank OF India, Mumbai Regional Office, Fort, Mumbai - 400001', '22642836', 'NA', 'RBIS0GSTPMT', 18839);
INSERT INTO bank_branch_t VALUES('Agartala', 'Agartala', 'II Floor, Jackson Gate Building Lenin Sarani, Agartala', '2381051', 'NA', 'RBIS0AGPA01', 18848);
