INSERT INTO bank_branch_t VALUES('Ahmedabad Regional Office', 'Ahmedabad', 'Pad,ahmedabad Main Office,ahmedabad', '0', 'NA', 'RBIS0AHPA01', 19397);
INSERT INTO bank_branch_t VALUES('PAD Bhubaneswar', 'Bhubaneswar', 'PAD Bhubaneswar, Bhubaneswar', '0', 'NA', 'RBIS0BBPA01', 19410);
INSERT INTO bank_branch_t VALUES('Bangalore Regional Office', 'Bangalore', '10 BY 3 BY 8, Nrupthunga Road, Bangalore-560 001', '0', 'NA', 'RBIS0BGPA01', 19401);
INSERT INTO bank_branch_t VALUES('PAD Bhopal', 'Bhopal', 'PAD Bhopal,bhopal', '0', 'NA', 'RBIS0BLPA01', 19405);
INSERT INTO bank_branch_t VALUES('PAD Chandigarh', 'Chandigarh', 'PAD Chandigarh,chandigarh', '0', 'NA', 'RBIS0CGPA01', 19393);
INSERT INTO bank_branch_t VALUES('Chennai Regional Office', 'Chennai', 'Pad,chennai Main Office,chennai', '0', 'NA', 'RBIS0CNPA01', 19412);
INSERT INTO bank_branch_t VALUES('Dehradun', 'Dehradun', '74 BY 1,rajpur Road,dehradun', '0', 'NA', 'RBIS0DNPA01', 19415);
INSERT INTO bank_branch_t VALUES('PAD Guwahati', 'Guwahati', 'PAD Guwahati', '0', 'NA', 'RBIS0GWPA01', 19391);
INSERT INTO bank_branch_t VALUES('Jammu', 'Jammu', 'Reserve Bank OF India,jammu', '0', 'NA', 'RBIS0JMPA01', 19399);
INSERT INTO bank_branch_t VALUES('Public Accounts Dept', 'Jaipur', 'Rambagh Circle,tonk Road,jaipur-302004', '0', 'NA', 'RBIS0JPPA01', 19411);
INSERT INTO bank_branch_t VALUES('Kochi', 'Kochi', 'Foreign Exchange Department , Reserve Bank OF India, Ernakulam North, Kochi 682018', '0', 'NA', 'RBIS0KCPA01', 19403);
INSERT INTO bank_branch_t VALUES('RBI PAD Kolkata', 'Kolkata', 'RBI Pad,kolkata', '0', 'NA', 'RBIS0KLPA01', 19416);
INSERT INTO bank_branch_t VALUES('PAD Kanpur', 'Kanpur', 'PAD Kanpur,kanpur', '0', 'NA', 'RBIS0KNPA01', 19413);
INSERT INTO bank_branch_t VALUES('RBI PAD Lucknow', 'Lucknow', 'RBI Pad, LUCKNOW.', '0', 'NA', 'RBIS0LKPA01', 19414);
INSERT INTO bank_branch_t VALUES('PAD Mumbai', 'Mumbai', 'PAD ,ground Floor,main Building ,fort Mumbai- 400001', '0', 'NA', 'RBIS0MBPA04', 19406);
INSERT INTO bank_branch_t VALUES('PAD NEW Delhi', 'NEW Delhi', '6, Sansad Marg , NEW Delhi 110001', '0', 'NA', 'RBIS0NDPA01', 19395);
INSERT INTO bank_branch_t VALUES('RBI PAD', 'Hyderabad', 'Rbi,lakdikapul,hyderabad', '0', 'NA', 'RBIS0NEFTHY', 19390);
INSERT INTO bank_branch_t VALUES('PAD Nagpur', 'Nagpur', 'PAD Nagpur,nagpur', '0', 'NA', 'RBIS0NGPA01', 19407);
INSERT INTO bank_branch_t VALUES('CBD Belapur', 'Navi Mumbai', 'Plot NO.3,SECTOR 10,H.H. Nirmaladevi Marg,cbd,belapur, Navi Mumbai 400614', '0', 'NA', 'RBIS0NMPA01', 19408);
INSERT INTO bank_branch_t VALUES('Panaji', 'Panaji', 'Geras Imperium II 7TH Floor 70706 Patto Panaji GOA 403001', '0', 'NA', 'RBIS0PJPA01', 19396);
INSERT INTO bank_branch_t VALUES('PAD Patna', 'Patna', 'PAD Patna,patna', '0', 'NA', 'RBIS0PTPA01', 19392);
INSERT INTO bank_branch_t VALUES('CAB Pune', 'Pune', 'Ganesh Khind Road, Near Esquare', '0', 'NA', 'RBIS0PUPA01', 19409);
INSERT INTO bank_branch_t VALUES('Ranchi', 'Ranchi', '4TH FLOOR.RRDA BUILDING.KATCHEHRI Road,ranchi 834001. Jharkhand', '0', 'NA', 'RBIS0RNPA01', 19400);
INSERT INTO bank_branch_t VALUES('Raipur', 'Raipur', '54 BY 949,subhashish Parisar,satya Prem Vihar,mahadev Ghat Road,sundar Nagar,raipur 492 013', '0', 'NA', 'RBIS0RPPA01', 19394);
INSERT INTO bank_branch_t VALUES('Samadhan - HR Operations Unit', 'Bengaluru', 'Reserve Bank OF India, Bengaluru', '22180100', 'NA', 'RBIS0SAMADN', 19402);
INSERT INTO bank_branch_t VALUES('Shimla', 'NEW Shimla', 'Rural Planning AND Credit Department , B 478, Sector IV, NEW Shimla, Shimla 171009', '0', 'NA', 'RBIS0SMPA01', 19398);
INSERT INTO bank_branch_t VALUES('Trivandrum', 'Trivandrum', 'Reserve Bank OF India,trivandrum', '0', 'NA', 'RBIS0THPA01', 19404);
