INSERT INTO bank_branch_t VALUES('Samadhan - HR Operations Unit', 'Bengaluru', 'Reserve Bank OF India, Bengaluru', '22180100', 'NA', 'RBIS0SAMADN', 18743);
INSERT INTO bank_branch_t VALUES('CAB Pune', 'Pune', 'Ganesh Khind Road, Near Esquare', '0', 'NA', 'RBIS0PUPA01', 18750);
INSERT INTO bank_branch_t VALUES('Trivandrum', 'Trivandrum', 'Reserve Bank OF India, Trivandrum', '0', 'NA', 'RBIS0THPA01', 18745);
INSERT INTO bank_branch_t VALUES('Shimla', 'NEW Shimla', 'Rural Planning AND Credit Department, B 478, Sector IV, NEW Shimla, Shimla 171009', '0', 'NA', 'RBIS0SMPA01', 18739);
INSERT INTO bank_branch_t VALUES('Raipur', 'Raipur', '54 BY 949, Subhashish Parisar, Satya Prem Vihar, Mahadev Ghat Road, Sundar Nagar, Raipur 492 013', '0', 'NA', 'RBIS0RPPA01', 18735);
INSERT INTO bank_branch_t VALUES('Ranchi', 'Ranchi', '4TH FLOOR.RRDA BUILDING.KATCHEHRI Road, Ranchi 834001. Jharkhand', '0', 'NA', 'RBIS0RNPA01', 18741);
INSERT INTO bank_branch_t VALUES('PAD Patna', 'Patna', 'PAD Patna, Patna', '0', 'NA', 'RBIS0PTPA01', 18733);
INSERT INTO bank_branch_t VALUES('Panaji', 'Panaji', 'Geras Imperium II 7TH Floor 70706 Patto Panaji GOA 403001', '0', 'NA', 'RBIS0PJPA01', 18737);
INSERT INTO bank_branch_t VALUES('CBD Belapur', 'Navi Mumbai', 'Plot NO.3, Sector 10, H.H. Nirmaladevi Marg, Cbd, Belapur, Navi Mumbai 400614', '0', 'NA', 'RBIS0NMPA01', 18749);
INSERT INTO bank_branch_t VALUES('PAD Nagpur', 'Nagpur', 'PAD Nagpur, Nagpur', '0', 'NA', 'RBIS0NGPA01', 18748);
INSERT INTO bank_branch_t VALUES('RBI PAD', 'Hyderabad', 'Rbi, Lakdikapul, Hyderabad', '0', 'NA', 'RBIS0NEFTHY', 18731);
INSERT INTO bank_branch_t VALUES('PAD NEW Delhi', 'NEW Delhi', '6,sansad Marg, NEW Delhi 110001', '0', 'NA', 'RBIS0NDPA01', 18736);
INSERT INTO bank_branch_t VALUES('PAD Mumbai', 'Mumbai', 'Pad, Ground Floor, Main Building, Fort Mumbai- 400001', '0', 'NA', 'RBIS0MBPA04', 18747);
INSERT INTO bank_branch_t VALUES('RBI PAD Lucknow', 'Lucknow', 'RBI Pad, LUCKNOW.', '0', 'NA', 'RBIS0LKPA01', 18755);
INSERT INTO bank_branch_t VALUES('PAD Kanpur', 'Kanpur', 'PAD Kanpur, Kanpur', '0', 'NA', 'RBIS0KNPA01', 18754);
INSERT INTO bank_branch_t VALUES('RBI PAD Kolkata', 'Kolkata', 'RBI Pad, Kolkata', '0', 'NA', 'RBIS0KLPA01', 18757);
INSERT INTO bank_branch_t VALUES('Kochi', 'Kochi', 'Foreign Exchange Department, Reserve Bank OF India, Ernakulam North, Kochi 682018', '0', 'NA', 'RBIS0KCPA01', 18744);
INSERT INTO bank_branch_t VALUES('Public Accounts Dept', 'Jaipur', 'Rambagh Circle, Tonk Road, Jaipur-302004', '0', 'NA', 'RBIS0JPPA01', 18752);
INSERT INTO bank_branch_t VALUES('Jammu', 'Jammu', 'Reserve Bank OF India, Jammu', '0', 'NA', 'RBIS0JMPA01', 18740);
INSERT INTO bank_branch_t VALUES('PAD Guwahati', 'Guwahati', 'PAD Guwahati', '0', 'NA', 'RBIS0GWPA01', 18732);
INSERT INTO bank_branch_t VALUES('Dehradun', 'Dehradun', '74 BY 1, Rajpur Road, Dehradun', '0', 'NA', 'RBIS0DNPA01', 18756);
INSERT INTO bank_branch_t VALUES('Chennai Regional Office', 'Chennai', 'Pad, Chennai Main Office, Chennai', '0', 'NA', 'RBIS0CNPA01', 18753);
INSERT INTO bank_branch_t VALUES('PAD Chandigarh', 'Chandigarh', 'PAD Chandigarh, Chandigarh', '0', 'NA', 'RBIS0CGPA01', 18734);
INSERT INTO bank_branch_t VALUES('PAD Bhopal', 'Bhopal', 'PAD Bhopal, Bhopal', '0', 'NA', 'RBIS0BLPA01', 18746);
INSERT INTO bank_branch_t VALUES('Bangalore Regional Office', 'Bangalore', '10 BY 3 BY 8, Nrupthunga Road, Bangalore-560 001', '0', 'NA', 'RBIS0BGPA01', 18742);
INSERT INTO bank_branch_t VALUES('PAD Bhubaneswar', 'Bhubaneswar', 'PAD Bhubaneswar, Bhubaneswar', '0', 'NA', 'RBIS0BBPA01', 18751);
INSERT INTO bank_branch_t VALUES('Ahmedabad Regional Office', 'Ahmedabad', 'Pad, Ahmedabad Main Office, Ahmedabad', '0', 'NA', 'RBIS0AHPA01', 18738);
