INSERT INTO ipc VALUES ('Contents', '', 'N')
INSERT INTO ipc VALUES ('Sections', 'Particulars', 'N')
INSERT INTO ipc VALUES ('Chapter I', 'Introduction', 'N')
INSERT INTO ipc VALUES ('1', 'Title and extent of operation of the Code', 'Y')
INSERT INTO ipc VALUES ('2', 'Punishment of offences committed within India', 'Y')
INSERT INTO ipc VALUES ('3', 'Punishment of offences committed beyond but which by law may be tried within India', 'Y')
INSERT INTO ipc VALUES ('4', 'Extension of Code to extra-territorial offences', 'Y')
INSERT INTO ipc VALUES ('5', 'Certain laws not to be affected by this Act', 'Y')
INSERT INTO ipc VALUES ('Chapter II', 'General Explanations', 'N')
INSERT INTO ipc VALUES ('6', 'Definitions in the Code to be understood subject to exceptions', 'Y')
INSERT INTO ipc VALUES ('7', 'Sense of expression once explained', 'Y')
INSERT INTO ipc VALUES ('8', 'Gender', 'Y')
INSERT INTO ipc VALUES ('9', 'Number', 'Y')
INSERT INTO ipc VALUES ('10', 'Man, Woman', 'Y')
INSERT INTO ipc VALUES ('11', 'Person', 'Y')
INSERT INTO ipc VALUES ('12', 'Public', 'Y')
INSERT INTO ipc VALUES ('13', '[Titled Queen repealed by the Govt. of India (Adaptation of Indian Laws) Order,  1950]', 'N')
INSERT INTO ipc VALUES ('14', 'Servant of Government', 'Y')
INSERT INTO ipc VALUES ('15', '[Titled British India repealed by the Govt. of India (Adaptation of Indian Laws) Order,  1937]', 'N')
INSERT INTO ipc VALUES ('16', '[Titled Government of India repealed by the Govt. of India (Adaptation of Indian Laws) Order,  1937]', 'N')
INSERT INTO ipc VALUES ('17', 'Government', 'Y')
INSERT INTO ipc VALUES ('18', 'India', 'Y')
INSERT INTO ipc VALUES ('19', 'Judge', 'Y')
INSERT INTO ipc VALUES ('20', 'Court of Justice', 'Y')
INSERT INTO ipc VALUES ('21', 'Public Servant', 'Y')
INSERT INTO ipc VALUES ('22', 'Movable property', 'Y')
INSERT INTO ipc VALUES ('23', 'Wrongful gain', 'Y')
INSERT INTO ipc VALUES ('24', 'Dishonestly', 'Y')
INSERT INTO ipc VALUES ('25', 'Fraudulently', 'Y')
INSERT INTO ipc VALUES ('26', 'Reason to believe', 'Y')
INSERT INTO ipc VALUES ('27', 'Property in possession of wife, clerk or servant', 'Y')
INSERT INTO ipc VALUES ('28', 'Counterfeit', 'Y')
INSERT INTO ipc VALUES ('29', 'Document', 'Y')
INSERT INTO ipc VALUES ('30', 'Valuable security', 'Y')
INSERT INTO ipc VALUES ('31', 'A will', 'Y')
INSERT INTO ipc VALUES ('32', 'Words referring to acts include illegal omissions', 'Y')
INSERT INTO ipc VALUES ('33', 'Act, Omission', 'Y')
INSERT INTO ipc VALUES ('34', 'Acts done by several persons in furtherance of common intention', 'Y')
INSERT INTO ipc VALUES ('35', 'When such an act is criminal by reason of its being done with a criminal knowledge or intention', 'Y')
INSERT INTO ipc VALUES ('36', 'Effect caused partly by act and partly by omission', 'Y')
INSERT INTO ipc VALUES ('37', 'Co-operation by doing one of several acts constituting an offence', 'Y')
INSERT INTO ipc VALUES ('38', 'Persons concerned in criminal act may be guilty of different offences', 'Y')
INSERT INTO ipc VALUES ('39', 'Voluntarily', 'Y')
INSERT INTO ipc VALUES ('40', 'Offence', 'Y')
INSERT INTO ipc VALUES ('41', 'Special law', 'Y')
INSERT INTO ipc VALUES ('42', 'Local law', 'Y')
INSERT INTO ipc VALUES ('43', 'Illegal, Legally bound to do', 'Y')
INSERT INTO ipc VALUES ('44', 'Injury', 'Y')
INSERT INTO ipc VALUES ('45', 'Life', 'Y')
INSERT INTO ipc VALUES ('46', 'Death', 'Y')
INSERT INTO ipc VALUES ('47', 'Animal', 'Y')
INSERT INTO ipc VALUES ('48', 'Vessel', 'Y')
INSERT INTO ipc VALUES ('49', 'Year, Month', 'Y')
INSERT INTO ipc VALUES ('50', 'Section', 'Y')
INSERT INTO ipc VALUES ('51', 'Oath', 'Y')
INSERT INTO ipc VALUES ('52', 'Good faith', 'Y')
INSERT INTO ipc VALUES ('52A', 'Harbor', 'Y')
INSERT INTO ipc VALUES ('Chapter  III', 'Of Punishments', 'N')
INSERT INTO ipc VALUES ('53', 'Punishment', 'Y')
INSERT INTO ipc VALUES ('53A', 'Construction of reference to transportation', 'Y')
INSERT INTO ipc VALUES ('54', 'Commutation of sentence of death', 'Y')
INSERT INTO ipc VALUES ('55', 'Commutation of sentence of imprisonment for life', 'Y')
INSERT INTO ipc VALUES ('55A', 'Definition of appropriate Government', 'Y')
INSERT INTO ipc VALUES ('56', '[Titled Sentence of Europeans and Americans to penal servitude, proviso as to sentence for term exceeding ten years but not for life repealed by the Criminal Law (Removal of Racial Discriminations) Act, 1949, w.e.f. 6th. April, 1949]', 'N')
INSERT INTO ipc VALUES ('57', 'Fractions of terms of punishment', 'Y')
INSERT INTO ipc VALUES ('58', '[Titled Offenders sentenced to transportation how dealt with until transported repealed by the Code of Criminal Procedure (Amendment) Act, 1955, w.e.f. 1st. January, 1956]', 'N')
INSERT INTO ipc VALUES ('59', '[Titled Transportation instead of imprisonment repealed by the Code of Criminal Procedure (Amendment) Act, 1955, w.e.f. 1st. January, 1956]', 'N')
INSERT INTO ipc VALUES ('60', 'Sentence may be (in certain cases of imprisonment) wholly or partly rigorous or simple', 'Y')
INSERT INTO ipc VALUES ('61', '[Titled Sentence of forfeiture of property repealed by the Indian Penal Code (Amendment) Act, 1921]', 'N')
INSERT INTO ipc VALUES ('62', '[Titled Forfeiture of property in respect of offenders punishable with death, transportation or imprisonment repealed by the Indian Penal Code (Amendment) Act, 1921]', 'N')
INSERT INTO ipc VALUES ('63', 'Amount of fine', 'Y')
INSERT INTO ipc VALUES ('64', 'Sentence of imprisonment for non-payment of fine', 'Y')
INSERT INTO ipc VALUES ('65', 'Limit to imprisonment for non-payment of fine, when imprisonment and fine awardable', 'Y')
INSERT INTO ipc VALUES ('66', 'Description of imprisonment for non-payment of fine', 'Y')
INSERT INTO ipc VALUES ('67', 'Imprisonment for non-payment of fine, when offence punishable with fine only', 'Y')
INSERT INTO ipc VALUES ('68', 'Imprisonment to terminate on payment of fine', 'Y')
INSERT INTO ipc VALUES ('69', 'Termination of imprisonment on payment of proportional part of fine', 'Y')
INSERT INTO ipc VALUES ('70', 'Fine leviable within six years or during imprisonment-Death not to discharge property from liability', 'Y')
INSERT INTO ipc VALUES ('71', 'Limit of punishment of offence made up of several offences', 'Y')
INSERT INTO ipc VALUES ('72', 'Punishment of person guilty of one of several offences, the judgment stating that it is doubtful of which', 'Y')
INSERT INTO ipc VALUES ('73', 'Solitary confinement', 'Y')
INSERT INTO ipc VALUES ('74', 'Limit of solitary confinement', 'Y')
INSERT INTO ipc VALUES ('75', 'Enhanced punishment for certain offences under Chapter XII or Chapter XVII after previous conviction', 'Y')
INSERT INTO ipc VALUES ('Chapter IV', 'General Exceptions', 'N')
INSERT INTO ipc VALUES ('76', 'Act done by a person bound, or by mistake of fact believing himself bound, by law', 'Y')
INSERT INTO ipc VALUES ('77', 'Act of Judge when acting judicially', 'Y')
INSERT INTO ipc VALUES ('78', 'Act done pursuant to the judgment or order of Court', 'Y')
INSERT INTO ipc VALUES ('79', 'Act done by a person justified, or by mistake of fact believing himself justified, by law', 'Y')
INSERT INTO ipc VALUES ('80', 'Accident in doing a lawful act', 'Y')
INSERT INTO ipc VALUES ('81', 'Act likely to cause harm, but done without criminal intent, and to prevent other harm', 'Y')
INSERT INTO ipc VALUES ('82', 'Act of a child under seven years of age', 'Y')
INSERT INTO ipc VALUES ('83', 'Act of a child above seven and under twelve of immature understanding', 'Y')
INSERT INTO ipc VALUES ('84', 'Act of a person of-unsound mind', 'Y')
INSERT INTO ipc VALUES ('85', 'Act of a person incapable of judgment by reason of intoxication caused against his will', 'Y')
INSERT INTO ipc VALUES ('86', 'Offence requiring a particular intent or knowledge committed by one who is intoxicated', 'Y')
INSERT INTO ipc VALUES ('87', 'Act not intended and not known to be likely to cause death or grievous hurt, done by consent', 'Y')
INSERT INTO ipc VALUES ('88', 'Act not intended to cause death, done by consent in good faith for person''s benefit', 'Y')
INSERT INTO ipc VALUES ('89', 'Act done in good faith for benefit of child or insane person, by or by consent of guardian', 'Y')
INSERT INTO ipc VALUES ('90', 'Consent known to be given under fear or misconception', 'Y')
INSERT INTO ipc VALUES ('91', 'Exclusion of acts which are offences independently of harm caused', 'Y')
INSERT INTO ipc VALUES ('92', 'Act done in good faith for benefit of a person without consent', 'Y')
INSERT INTO ipc VALUES ('93', 'Communication made in good faith', 'Y')
INSERT INTO ipc VALUES ('94', 'Act to which a person is compelled by threats', 'Y')
INSERT INTO ipc VALUES ('95', 'Act causing slight harm', 'Y')
INSERT INTO ipc VALUES ('96', 'Things done in private defense', 'Y')
INSERT INTO ipc VALUES ('97', 'Right of private defense of the body and of property', 'Y')
INSERT INTO ipc VALUES ('98', 'Right of private defense against the act of a person of unsound mind, etc.', 'Y')
INSERT INTO ipc VALUES ('99', 'Acts against which there is no right of private defense', 'Y')
INSERT INTO ipc VALUES ('100', 'When the right of private defense of the body extends to causing death', 'Y')
INSERT INTO ipc VALUES ('101', 'When such right extends to causing any harm other than death', 'Y')
INSERT INTO ipc VALUES ('102', 'Commencement and continuance of the right of private defense of the body', 'Y')
INSERT INTO ipc VALUES ('103', 'When the right of private defense of property extends to causing death', 'Y')
INSERT INTO ipc VALUES ('104', 'When such right extends to causing any harm other than death', 'Y')
INSERT INTO ipc VALUES ('105', 'Commencement and continuance of the right of private defense of property', 'Y')
INSERT INTO ipc VALUES ('106', 'Right of private defense against deadly assault when there is risk of harm to innocent person', 'Y')
INSERT INTO ipc VALUES ('Chapter V', 'Of Abetment', 'N')
INSERT INTO ipc VALUES ('107', 'Abetment of a thing', 'Y')
INSERT INTO ipc VALUES ('108', 'Abettor', 'Y')
INSERT INTO ipc VALUES ('108A', 'Abetment in India of offences outside India', 'Y')
INSERT INTO ipc VALUES ('109', 'Punishment of abetment if the act abetted is committed in consequence, and where no express provision is made for its punishment', 'Y')
INSERT INTO ipc VALUES ('110', 'Punishment of abetment if person abetted does act with different intention from that of abettor', 'Y')
INSERT INTO ipc VALUES ('111', 'Liability of abettor when one act abetted and different act done', 'Y')
INSERT INTO ipc VALUES ('112', 'Abettor when liable to cumulative punishment for act abetted and for act done', 'Y')
INSERT INTO ipc VALUES ('113', 'Liability of abettor for an effect caused by the act abetted different from that intended by the abettor', 'Y')
INSERT INTO ipc VALUES ('114', 'Abettor present when offence is committed', 'Y')
INSERT INTO ipc VALUES ('115', 'Abetment of offence punishable with death or imprisonment for life-if offence not committed', 'Y')
INSERT INTO ipc VALUES ('116', 'Abetment of offence punishable with imprisonment-if offence be not committed', 'Y')
INSERT INTO ipc VALUES ('117', 'Abetting commission of offence by the public or by more than ten persons', 'Y')
INSERT INTO ipc VALUES ('118', 'Concealing design to commit offence punishable with death or imprisonment for life', 'Y')
INSERT INTO ipc VALUES ('119', 'Public servant concealing design to commit offence which it is his duty to prevent', 'Y')
INSERT INTO ipc VALUES ('120', 'Concealing design to commit offence punishable with imprisonment', 'Y')
INSERT INTO ipc VALUES ('Chapter V(A)', 'A Criminal Conspiracy', 'N')
INSERT INTO ipc VALUES ('120A', 'Definition of criminal conspiracy', 'Y')
INSERT INTO ipc VALUES ('120B', 'Punishment of criminal conspiracy', 'Y')
INSERT INTO ipc VALUES ('Chapter  VI ', 'Of Offences Against The State', 'N')
INSERT INTO ipc VALUES ('121', 'Waging, or attempting to wage war, or abetting waging of war, against the Government of India', 'Y')
INSERT INTO ipc VALUES ('121A', 'Conspiracy to commit offences punishable by section 121', 'Y')
INSERT INTO ipc VALUES ('122', 'Collecting arms, etc., with intention of waging war against the Government of India', 'Y')
INSERT INTO ipc VALUES ('123', 'Concealing with intent to facilitate design to wage war', 'Y')
INSERT INTO ipc VALUES ('124', 'Assaulting President, Governor, etc., with intent to compel or restrain the exercise of any lawful power', 'Y')
INSERT INTO ipc VALUES ('124A', 'Sedition', 'Y')
INSERT INTO ipc VALUES ('125', 'Waging war against any Asiatic Power in alliance with the Government of India', 'Y')
INSERT INTO ipc VALUES ('126', 'Committing depredation on territories of Power at peace with the Government of India', 'Y')
INSERT INTO ipc VALUES ('127', 'Receiving property taken by war on depredation mentioned in sections 125 and 126-', 'Y')
INSERT INTO ipc VALUES ('128', 'Public servant voluntarily allowing prisoner of State or war to escape', 'Y')
INSERT INTO ipc VALUES ('129', 'Public servant negligently suffering such prisoner to escape', 'Y')
INSERT INTO ipc VALUES ('130', 'Aiding escape of, rescuing or harboring such prisoner', 'Y')
INSERT INTO ipc VALUES ('Chapter VII', 'Of Offences Relating To The Army ,74[Navy And Air Force]', 'N')
INSERT INTO ipc VALUES ('131', 'Abetting mutiny, or attempting to seduce a soldier, sailor or airman from his duty', 'Y')
INSERT INTO ipc VALUES ('132', 'Abetment of mutiny, if mutiny is committed in consequence thereof', 'Y')
INSERT INTO ipc VALUES ('133', 'Abetment of assault by soldier, sailor or airman on his superior officer, when in execution of his office', 'Y')
INSERT INTO ipc VALUES ('134', 'Abetment of such assault, if the assault is committed', 'Y')
INSERT INTO ipc VALUES ('135', 'Abetment of desertion of soldier, sailor or airman', 'Y')
INSERT INTO ipc VALUES ('136', 'Harboring deserter', 'Y')
INSERT INTO ipc VALUES ('137', 'Deserter concealed on board merchant vessel through negligence of master', 'Y')
INSERT INTO ipc VALUES ('138', 'Abetment of act of insubordination by soldier, sailor or airman', 'Y')
INSERT INTO ipc VALUES ('138A', '[Titled Application of foregoing sections to the Indian Marine Service repealed by the Amending Act, 1934 (35 of 1934)]', 'N')
INSERT INTO ipc VALUES ('139', 'Persons subject to certain Acts', 'Y')
INSERT INTO ipc VALUES ('140', 'Wearing garb or carrying token used by soldier, sailor or airman', 'Y')
INSERT INTO ipc VALUES ('Chapter VIII ', 'Of Offences Against The Public Tranquillity', 'N')
INSERT INTO ipc VALUES ('141', 'Unlawful assembly', 'Y')
INSERT INTO ipc VALUES ('142', 'Being member of unlawful assembly', 'Y')
INSERT INTO ipc VALUES ('143', 'Punishment', 'Y')
INSERT INTO ipc VALUES ('144', 'Joining unlawful assembly armed with deadly weapon', 'Y')
INSERT INTO ipc VALUES ('145', 'Joining or continuing in unlawful assembly, knowing it has been commanded to disperse', 'Y')
INSERT INTO ipc VALUES ('146', 'Rioting', 'Y')
INSERT INTO ipc VALUES ('147', 'Punishment for rioting', 'Y')
INSERT INTO ipc VALUES ('148', 'Rioting, armed with deadly weapon', 'Y')
INSERT INTO ipc VALUES ('149', 'Every member of unlawful assembly guilty of offence committed in prosecution of common object', 'Y')
INSERT INTO ipc VALUES ('150', 'Hiring, or conniving at hiring, of persons to join unlawful assembly', 'Y')
INSERT INTO ipc VALUES ('151', 'Knowingly joining or continuing in assembly of five or more persons after it has been commanded to disperse', 'Y')
INSERT INTO ipc VALUES ('152', 'Assaulting or obstructing public servant when suppressing riot, etc.', 'Y')
INSERT INTO ipc VALUES ('153', 'Wantonly giving provocation with intent to cause riot-if rioting be committed-if not committed', 'Y')
INSERT INTO ipc VALUES ('153A', 'Promoting enmity between different groups on grounds of religion, race, place of birth, residence, language, etc., and doing acts prejudicial to maintenance of harmony', 'Y')
INSERT INTO ipc VALUES ('153B', 'Imputations, assertions prejudicial to national-integration', 'Y')
INSERT INTO ipc VALUES ('154', 'Owner or occupier of land on which an unlawful assembly is held', 'Y')
INSERT INTO ipc VALUES ('155', 'Liability of person for whose benefit riot is committed', 'Y')
INSERT INTO ipc VALUES ('156', 'Liability of agent of owner or occupier for whose benefit riot is committed', 'Y')
INSERT INTO ipc VALUES ('157', 'Harboring persons hired for an unlawful assembly', 'Y')
INSERT INTO ipc VALUES ('158', 'Being hired to take part in an unlawful assembly or riot', 'Y')
INSERT INTO ipc VALUES ('159', 'Affray', 'Y')
INSERT INTO ipc VALUES ('160', 'Punishment for committing affray', 'Y')
INSERT INTO ipc VALUES ('Chapter IX ', 'Of Offences By Or Relating To Public Servants', 'N')
INSERT INTO ipc VALUES ('161', '[To 165A. repealed by the Prevention of Corruption Act, 1988 (49 of 1988)]', 'N')
INSERT INTO ipc VALUES ('166', 'Public servant disobeying law, with intent to cause injury to any person', 'Y')
INSERT INTO ipc VALUES ('167', 'Public servant framing an incorrect document with intent to cause injury', 'Y')
INSERT INTO ipc VALUES ('168', 'Public servant unlawfully engaging in trade', 'Y')
INSERT INTO ipc VALUES ('169', 'Public servant unlawfully buying or bidding for property', 'Y')
INSERT INTO ipc VALUES ('170', 'Personating a public servant', 'Y')
INSERT INTO ipc VALUES ('171', 'Wearing garb or carrying token used by public servant with fraudulent intent', 'Y')
INSERT INTO ipc VALUES ('Chapter IXA', 'Of Offences Relating To Elections', 'N')
INSERT INTO ipc VALUES ('171A', 'Candidate, Electoral right defined', 'Y')
INSERT INTO ipc VALUES ('171B', 'Bribery', 'Y')
INSERT INTO ipc VALUES ('171C', 'Undue influence at elections', 'Y')
INSERT INTO ipc VALUES ('171D', 'Personation at elections', 'Y')
INSERT INTO ipc VALUES ('171E', 'Punishment for bribery', 'Y')
INSERT INTO ipc VALUES ('171F', 'Punishment for undue influence or personation at an election', 'Y')
INSERT INTO ipc VALUES ('171G', 'False statement in connection with an election', 'Y')
INSERT INTO ipc VALUES ('171H', 'Illegal payments in connection with an election', 'Y')
INSERT INTO ipc VALUES ('171I', 'Failure to keep election accounts', 'Y')
INSERT INTO ipc VALUES ('Chapter X ', 'Of Contempts Of The Lawful Authority Of Public Servants', 'N')
INSERT INTO ipc VALUES ('172', 'Absconding to avoid service of summons or other proceeding', 'Y')
INSERT INTO ipc VALUES ('173', 'Preventing service of summons or other proceeding, or preventing publication thereof', 'Y')
INSERT INTO ipc VALUES ('174', 'Non-attendance in obedience to an order from public servant', 'Y')
INSERT INTO ipc VALUES ('175', 'Omission to produce document to public servant by person legally bound to produce it', 'Y')
INSERT INTO ipc VALUES ('176', 'Omission to give notice or information to public servant by person legally bound to give it', 'Y')
INSERT INTO ipc VALUES ('177', 'Furnishing false information', 'Y')
INSERT INTO ipc VALUES ('178', 'Refusing oath or affirmation when duly required by public servant to make it', 'Y')
INSERT INTO ipc VALUES ('179', 'Refusing to answer public servant authorized to question', 'Y')
INSERT INTO ipc VALUES ('180', 'Refusing to sign statement', 'Y')
INSERT INTO ipc VALUES ('181', 'False statement on oath or affirmation to public servant or person authorized to administer an oath or affirmation', 'Y')
INSERT INTO ipc VALUES ('182', 'False information, with intent to cause public servant to use his lawful power to the injury of another person', 'Y')
INSERT INTO ipc VALUES ('183', 'Resistance to the taking of property by the lawful authority of a public servant', 'Y')
INSERT INTO ipc VALUES ('184', 'Obstructing sale of property offered for sale by authority of public servant', 'Y')
INSERT INTO ipc VALUES ('185', 'Illegal purchase or bid for property offered for sale by authority of public servant', 'Y')
INSERT INTO ipc VALUES ('186', 'Obstructing public servant in discharge of public functions', 'Y')
INSERT INTO ipc VALUES ('187', 'Omission to assist public servant when bound by law to give assistance', 'Y')
INSERT INTO ipc VALUES ('188', 'Disobedience to order duly promulgated by public servant', 'Y')
INSERT INTO ipc VALUES ('189', 'Threat of injury to public servant', 'Y')
INSERT INTO ipc VALUES ('190', 'Threat of injury to induce person to refrain from applying for protection to public servant', 'Y')
INSERT INTO ipc VALUES ('Chapter XI ', 'Of False Evidence And Offences Against Public Justice', 'N')
INSERT INTO ipc VALUES ('191', 'Giving false evidence', 'Y')
INSERT INTO ipc VALUES ('192', 'Fabricating false evidence', 'Y')
INSERT INTO ipc VALUES ('193', 'Punishment for false evidence', 'Y')
INSERT INTO ipc VALUES ('194', 'Giving or fabricating false evidence with intent to procure conviction of capital offence', 'Y')
INSERT INTO ipc VALUES ('195', 'Giving or fabricating false evidence with intent to procure conviction of offence punishable with imprisonment for life or imprisonment', 'Y')
INSERT INTO ipc VALUES ('196', 'Using evidence known to be false', 'Y')
INSERT INTO ipc VALUES ('197', 'Issuing or signing false certificate', 'Y')
INSERT INTO ipc VALUES ('198', 'Using as true a certificate known to be false', 'Y')
INSERT INTO ipc VALUES ('199', 'False statement made in declaration which is by law receivable as evidence', 'Y')
INSERT INTO ipc VALUES ('200', 'Using as true such declaration knowing it to be false', 'Y')
INSERT INTO ipc VALUES ('201', 'Causing disappearance of evidence of offence, or giving false information to screen offender', 'Y')
INSERT INTO ipc VALUES ('202', 'Intentional omission to give information of offence by person bound to inform', 'Y')
INSERT INTO ipc VALUES ('203', 'Giving false information respecting an offence committed', 'Y')
INSERT INTO ipc VALUES ('204', 'Destruction of document to prevent its production as evidence', 'Y')
INSERT INTO ipc VALUES ('205', 'False personation for purpose of act or proceeding in suit or prosecution', 'Y')
INSERT INTO ipc VALUES ('206', 'Fraudulent removal or concealment of property to prevent its seizure as forfeited or in execution', 'Y')
INSERT INTO ipc VALUES ('207', 'Fraudulent claim to property to prevent its seizure as forfeited or in execution', 'Y')
INSERT INTO ipc VALUES ('208', 'Fraudulently suffering decree for sum not due', 'Y')
INSERT INTO ipc VALUES ('209', 'Dishonestly making false claim in Court', 'Y')
INSERT INTO ipc VALUES ('210', 'Fraudulently obtaining decree for sum not due', 'Y')
INSERT INTO ipc VALUES ('211', 'False charge of offence made with intent to injure', 'Y')
INSERT INTO ipc VALUES ('212', 'Harboring offender', 'Y')
INSERT INTO ipc VALUES ('213', 'Taking gift, etc., to screen an offender from punishment', 'Y')
INSERT INTO ipc VALUES ('214', 'Offering gift or restoration of property in consideration of screening offender', 'Y')
INSERT INTO ipc VALUES ('215', 'Taking gift to help to recover stolen property, etc', 'Y')
INSERT INTO ipc VALUES ('216', 'Harboring offender who has escaped from custody or whose apprehension has been ordered', 'Y')
INSERT INTO ipc VALUES ('216A', 'Penalty for harboring robbers or dacoits', 'Y')
INSERT INTO ipc VALUES ('216B    ', '[Definition of harbor in sections 212, 216 and 216A: Repealed by the Indian Penal Code (Amendment) Act, 1942 (8 of 1942)]', 'N')
INSERT INTO ipc VALUES ('217', 'Public servant disobeying direction of law with intent to save person from punishment or property from forfeiture', 'Y')
INSERT INTO ipc VALUES ('218', 'Public servant framing incorrect record or writing with intent to save person from punishment or property from forfeiture', 'Y')
INSERT INTO ipc VALUES ('219', 'Public servant in judicial proceeding corruptly making report, etc., contrary to law', 'Y')
INSERT INTO ipc VALUES ('220', 'Commitment for trial or confinement by person having authority who knows that he is acting contrary to law', 'Y')
INSERT INTO ipc VALUES ('221', 'Intentional omission to apprehend on the part of public servant bound to apprehend', 'Y')
INSERT INTO ipc VALUES ('222', 'Intentional omission to apprehend on the part of public servant bound to apprehend person under sentence or lawfully committed', 'Y')
INSERT INTO ipc VALUES ('223', 'Escape from confinement or custody negligently suffered by public servant', 'Y')
INSERT INTO ipc VALUES ('224', 'Resistance or obstruction by a person to his lawful apprehension', 'Y')
INSERT INTO ipc VALUES ('225', 'Resistance or obstruction to lawful apprehension of another person', 'Y')
INSERT INTO ipc VALUES ('225A', 'Omission to apprehend, or sufferance of escape, on part of public servant, in cases not otherwise, provided for', 'Y')
INSERT INTO ipc VALUES ('225B', 'Resistance or obstruction to lawful apprehension, or escape or rescue in cases not otherwise provided for', 'Y')
INSERT INTO ipc VALUES ('226.     ', '[Unlawful return from transportation: Repealed by the Code of Criminal Procedure (Amendment) Act, 1995, w.e.f. 1st. January, 1956]', 'N')
INSERT INTO ipc VALUES ('227', 'Violation of condition of remission of punishment', 'Y')
INSERT INTO ipc VALUES ('228', 'Intentional insult or interruption to public servant sitting in judicial proceeding', 'Y')
INSERT INTO ipc VALUES ('228A', 'Disclosure of identity of the victim of certain offences etc', 'Y')
INSERT INTO ipc VALUES ('229', 'Personation of a juror or assessor', 'Y')
INSERT INTO ipc VALUES ('Chapter XII', 'Of Offences Relating To Coin And Government Stamps', 'N')
INSERT INTO ipc VALUES ('230', 'Coin defined', 'Y')
INSERT INTO ipc VALUES ('231', 'Counterfeiting coin', 'Y')
INSERT INTO ipc VALUES ('232', 'Counterfeiting Indian coin', 'Y')
INSERT INTO ipc VALUES ('233', 'Making or selling instrument for counterfeiting coin', 'Y')
INSERT INTO ipc VALUES ('234', 'Making or selling instrument for counterfeiting Indian coin', 'Y')
INSERT INTO ipc VALUES ('235', 'Possession of instrument, or material for the purpose of using the same for counterfeiting coin', 'Y')
INSERT INTO ipc VALUES ('236', 'Abetting in India the counterfeiting out of India of coin', 'Y')
INSERT INTO ipc VALUES ('237', 'Import or export of counterfeit coin', 'Y')
INSERT INTO ipc VALUES ('238', 'Import or export of counterfeits of the India coin', 'Y')
INSERT INTO ipc VALUES ('239', 'Delivery of coin, possessed with knowledge that it is counterfeit', 'Y')
INSERT INTO ipc VALUES ('240', 'Delivery of Indian coin, possessed with knowledge that it is counterfeit', 'Y')
INSERT INTO ipc VALUES ('241', 'Delivery of coin as genuine, which, when first possessed, the deliverer did not know to be counterfeit', 'Y')
INSERT INTO ipc VALUES ('242', 'Possession of counterfeit coin by person who knew it to be counterfeit when he became possessed thereof-', 'Y')
INSERT INTO ipc VALUES ('243', 'Possession of Indian coin by person who knew it to be counterfeit when he became possessed thereof', 'Y')
INSERT INTO ipc VALUES ('244', 'Person employed in mint causing coin to be of different weight or composition from that fixed by law', 'Y')
INSERT INTO ipc VALUES ('245', 'Unlawfully taking coining instrument from mint', 'Y')
INSERT INTO ipc VALUES ('246', 'Fraudulently or dishonestly diminishing weight or altering composition of coin', 'Y')
INSERT INTO ipc VALUES ('247', 'Fraudulently or dishonestly diminishing weight or altering composition of Indian coin', 'Y')
INSERT INTO ipc VALUES ('248', 'Altering appearance of coin with intent that it shall pass as coin of different description', 'Y')
INSERT INTO ipc VALUES ('249', 'Altering appearance of Indian coin with intent that it shall pass as coin of different description', 'Y')
INSERT INTO ipc VALUES ('250', 'Delivery of coin, possessed with knowledge that it is altered', 'Y')
INSERT INTO ipc VALUES ('251', 'Delivery of Indian coin, possessed with knowledge that it is altered', 'Y')
INSERT INTO ipc VALUES ('252', 'Possession of coin by person who knew it to be altered when he became possessed thereof-', 'Y')
INSERT INTO ipc VALUES ('253', 'Possession of Indian coin by person who knew it to be altered when he became possessed thereof-', 'Y')
INSERT INTO ipc VALUES ('254', 'Delivery of coin as genuine, which, when first possessed, the deliverer did not know to be altered', 'N')
INSERT INTO ipc VALUES ('255', 'Counterfeiting Government stamp', 'Y')
INSERT INTO ipc VALUES ('256', 'Having possession of instrument or material for counterfeiting Government stamp', 'Y')
INSERT INTO ipc VALUES ('257', 'Making or selling instrument for counterfeiting Government stamp', 'Y')
INSERT INTO ipc VALUES ('258', 'Sale of counterfeit Government stamp', 'Y')
INSERT INTO ipc VALUES ('259', 'Having possession of counterfeit Government stamp', 'Y')
INSERT INTO ipc VALUES ('260', 'Using as genuine a Government stamp known to be a counterfeit', 'Y')
INSERT INTO ipc VALUES ('261', 'Effacing, writing from substance bearing Government stamp, or removing from document a stamp used for it, with intent to cause loss to Government', 'Y')
INSERT INTO ipc VALUES ('262', 'Using Government stamp known to have been before used', 'Y')
INSERT INTO ipc VALUES ('263', 'Erasure of mark denoting that stamp has been used', 'Y')
INSERT INTO ipc VALUES ('263A    ', 'Prohibition of fictitious stamps', 'Y')
INSERT INTO ipc VALUES ('Chapter XIII ', 'Of Offences Relating To Weights And Measures', 'N')
INSERT INTO ipc VALUES ('264', 'Fraudulent use of false instrument for weighing', 'Y')
INSERT INTO ipc VALUES ('265', 'Fraudulent use of false weight or measure', 'Y')
INSERT INTO ipc VALUES ('266', 'Being in possession of false weight or measure', 'Y')
INSERT INTO ipc VALUES ('267', 'Making or selling false weight or measure', 'Y')
INSERT INTO ipc VALUES ('Chapter XIV ', 'Of Offences Affecting The Public Health, Safety, Convenience, Decency And Morals', 'N')
INSERT INTO ipc VALUES ('268', 'Public nuisance Public nuisance', 'Y')
INSERT INTO ipc VALUES ('269', 'Negligent act likely to spread infection of disease dangerous to life', 'Y')
INSERT INTO ipc VALUES ('270', 'Malignant act likely to spread infection of disease dangerous to life', 'Y')
INSERT INTO ipc VALUES ('271', 'Disobedience to quarantine rule', 'Y')
INSERT INTO ipc VALUES ('272', 'Adulteration of food or drink intended for sale', 'Y')
INSERT INTO ipc VALUES ('273', 'Sale of noxious food or drink', 'Y')
INSERT INTO ipc VALUES ('274', 'Adulteration of drugs', 'Y')
INSERT INTO ipc VALUES ('275', 'Sale of adulterated drugs', 'Y')
INSERT INTO ipc VALUES ('276', 'Sale of drug as a different drug or preparation', 'Y')
INSERT INTO ipc VALUES ('277', 'Fouling water of public spring or reservoir', 'Y')
INSERT INTO ipc VALUES ('278', 'Making atmosphere noxious to health', 'Y')
INSERT INTO ipc VALUES ('279', 'Rash driving or riding on a public way', 'Y')
INSERT INTO ipc VALUES ('280', 'Rash navigation of vessel', 'Y')
INSERT INTO ipc VALUES ('281', 'Exhibition of false light, mark or buoy', 'Y')
INSERT INTO ipc VALUES ('282', 'Conveying person by water for hire in unsafe or overloaded vessel-', 'Y')
INSERT INTO ipc VALUES ('283', 'Danger or obstruction in public way or line of navigation', 'Y')
INSERT INTO ipc VALUES ('284', 'Negligent conduct with respect to poisonous substance', 'Y')
INSERT INTO ipc VALUES ('285', 'Negligent conduct with respect to fire or combustible matter', 'Y')
INSERT INTO ipc VALUES ('286', 'Negligent conduct with respect to explosive substance', 'Y')
INSERT INTO ipc VALUES ('287', 'Negligent conduct with respect to machinery', 'Y')
INSERT INTO ipc VALUES ('288', 'Negligent conduct with respect to pulling down or repairing buildings', 'Y')
INSERT INTO ipc VALUES ('289', 'Negligent conduct with respect to animal', 'Y')
INSERT INTO ipc VALUES ('290', 'Punishment for public nuisance in cases not otherwise provided for', 'Y')
INSERT INTO ipc VALUES ('291', 'Continuance of nuisance after injunction to discontinue', 'Y')
INSERT INTO ipc VALUES ('292', 'Sale, etc., of obscene books, etc. _', 'Y')
INSERT INTO ipc VALUES ('292A', 'Printing, etc., of grossly indecent or scurrilous matter or matter intended for blackmail', 'Y')
INSERT INTO ipc VALUES ('293', 'Sale, etc., of obscene objects to young person', 'Y')
INSERT INTO ipc VALUES ('294', 'Obscene acts and songs', 'Y')
INSERT INTO ipc VALUES ('294A', 'Keeping lottery office', 'Y')
INSERT INTO ipc VALUES ('Chapter XV ', 'Of Offences Relating To Religion', 'N')
INSERT INTO ipc VALUES ('295', 'Injuring or defiling place of worship with intent to insult the religion of any class', 'Y')
INSERT INTO ipc VALUES ('295A    ', 'Deliberate and malicious acts, intended to outrage religious feelings of any class by insulting its religion or religious beliefs', 'Y')
INSERT INTO ipc VALUES ('296', 'Disturbing religious assembly', 'Y')
INSERT INTO ipc VALUES ('297', 'Trespassing on burial places, etc', 'Y')
INSERT INTO ipc VALUES ('298', 'Uttering, words, etc., with deliberate intent to wound the religious feelings of any person-', 'Y')
INSERT INTO ipc VALUES ('Chapter XVI ', 'Of Offences Affecting The Human Body', 'N')
INSERT INTO ipc VALUES ('299', 'Culpable homicide', 'Y')
INSERT INTO ipc VALUES ('300', 'Murder', 'Y')
INSERT INTO ipc VALUES ('301', 'Culpable homicide by causing death of person other than person whose death was intended', 'Y')
INSERT INTO ipc VALUES ('302', 'Punishment for murder', 'Y')
INSERT INTO ipc VALUES ('303', 'Punishment for murder by life-convict', 'Y')
INSERT INTO ipc VALUES ('304', 'Punishment for culpable homicide not amounting to murder', 'Y')
INSERT INTO ipc VALUES ('304A', 'Causing death by negligence', 'Y')
INSERT INTO ipc VALUES ('304B', 'Dowry death', 'Y')
INSERT INTO ipc VALUES ('305', 'Abetment of suicide of child or insane person', 'Y')
INSERT INTO ipc VALUES ('306', 'Abetment of suicide', 'Y')
INSERT INTO ipc VALUES ('307', 'Attempt to murder', 'Y')
INSERT INTO ipc VALUES ('308', 'Attempt to commit culpable homicide', 'Y')
INSERT INTO ipc VALUES ('309', 'Attempt to commit suicide', 'Y')
INSERT INTO ipc VALUES ('310', 'Thug', 'Y')
INSERT INTO ipc VALUES ('311', 'Punishment', 'Y')
INSERT INTO ipc VALUES ('312', 'Causing miscarriage', 'Y')
INSERT INTO ipc VALUES ('313', 'Causing miscarriage without woman''s consent', 'Y')
INSERT INTO ipc VALUES ('314', 'Death caused by act done with intent to cause miscarriage', 'Y')
INSERT INTO ipc VALUES ('315', 'Act done with intent to prevent child being born alive or to cause it to die after birth', 'Y')
INSERT INTO ipc VALUES ('316', 'Causing death of quick unborn child by act amounting to culpable homicide', 'Y')
INSERT INTO ipc VALUES ('317', 'Exposure and abandonment of child under twelve years, by parent or person having care of it', 'Y')
INSERT INTO ipc VALUES ('318', 'Concealment of birth by secret disposal of dead body', 'Y')
INSERT INTO ipc VALUES ('319', 'Hurt', 'Y')
INSERT INTO ipc VALUES ('320', 'Grievous hurt', 'Y')
INSERT INTO ipc VALUES ('321', 'Voluntarily causing hurt', 'Y')
INSERT INTO ipc VALUES ('322', 'Voluntarily causing grievous hurt', 'Y')
INSERT INTO ipc VALUES ('323', 'Punishment for voluntarily causing hurt', 'Y')
INSERT INTO ipc VALUES ('324', 'Voluntarily causing hurt by dangerous weapons or means', 'Y')
INSERT INTO ipc VALUES ('325', 'Punishment for voluntarily causing grievous hurt', 'Y')
INSERT INTO ipc VALUES ('326', 'Voluntarily causing grievous hurt by dangerous weapons or means -', 'Y')
INSERT INTO ipc VALUES ('327', 'Voluntarily causing hurt to extort property, or to constrain to an illegal act', 'Y')
INSERT INTO ipc VALUES ('328', 'Causing hurt by means of poison, etc. with intent to commit an offence', 'Y')
INSERT INTO ipc VALUES ('329', 'Voluntarily causing grievous hurt to extort property, or to constrain to an illegal act', 'Y')
INSERT INTO ipc VALUES ('330', 'Voluntarily causing hurt to extort confession, or to compel restoration of property', 'Y')
INSERT INTO ipc VALUES ('331', 'Voluntarily causing grievous hurt to extort confession, or to compel restoration of property', 'Y')
INSERT INTO ipc VALUES ('332', 'Voluntarily causing hurt to deter public servant from his duty', 'Y')
INSERT INTO ipc VALUES ('333', 'Voluntarily causing grievous hurt to deter public servant from his duty', 'Y')
INSERT INTO ipc VALUES ('334', 'Voluntarily causing hurt on provocation', 'Y')
INSERT INTO ipc VALUES ('335', 'Voluntarily causing grievous hurt on provocation', 'Y')
INSERT INTO ipc VALUES ('336', 'Act endangering life or personal safety of others', 'Y')
INSERT INTO ipc VALUES ('337', 'Causing hurt by act endangering life or personal safety of others', 'Y')
INSERT INTO ipc VALUES ('338', 'Causing grievous hurt by act endangering life or personal safety of others', 'Y')
INSERT INTO ipc VALUES ('339', 'Wrongful restraint', 'Y')
INSERT INTO ipc VALUES ('340', 'Wrongful confinement', 'Y')
INSERT INTO ipc VALUES ('341', 'Punishment for wrongful restraint', 'Y')
INSERT INTO ipc VALUES ('342', 'Punishment for wrongful confinement', 'Y')
INSERT INTO ipc VALUES ('343', 'Wrongful confinement for three or more days', 'Y')
INSERT INTO ipc VALUES ('344', 'Wrongful confinement for ten or more days', 'Y')
INSERT INTO ipc VALUES ('345', 'Wrongful confinement of person for whose liberation writ has been issued', 'Y')
INSERT INTO ipc VALUES ('346', 'Wrongful confinement in secret', 'Y')
INSERT INTO ipc VALUES ('347', 'Wrongful confinement to extort property, or constrain to illegal act', 'Y')
INSERT INTO ipc VALUES ('348', 'Wrongful confinement to extort confession, or compel restoration of property', 'Y')
INSERT INTO ipc VALUES ('349', 'Force', 'Y')
INSERT INTO ipc VALUES ('350', 'Criminal force', 'Y')
INSERT INTO ipc VALUES ('351', 'Assault', 'Y')
INSERT INTO ipc VALUES ('352', 'Punishment for assault or criminal force otherwise than on grave provocation', 'Y')
INSERT INTO ipc VALUES ('353', 'Assault or criminal force to deter public servant from discharge of his duty', 'Y')
INSERT INTO ipc VALUES ('354', 'Assault or criminal force to woman with intent to outrage her modesty.', 'Y')
INSERT INTO ipc VALUES ('355', 'Assault or criminal force with intent to dishonor person, otherwise than on grave provocation', 'Y')
INSERT INTO ipc VALUES ('356', 'Assault or criminal force in attempt to commit theft of property carried by a person', 'Y')
INSERT INTO ipc VALUES ('357', 'Assault or criminal force in attempt wrongfully to confine a person', 'Y')
INSERT INTO ipc VALUES ('358', 'Assault or criminal force on grave provocation', 'Y')
INSERT INTO ipc VALUES ('359', 'Kidnapping', 'Y')
INSERT INTO ipc VALUES ('360', 'Kidnapping from India', 'Y')
INSERT INTO ipc VALUES ('361', 'Kidnapping from lawful guardianship', 'Y')
INSERT INTO ipc VALUES ('362', 'Abduction', 'Y')
INSERT INTO ipc VALUES ('363', 'Punishment for kidnapping', 'Y')
INSERT INTO ipc VALUES ('363A    ', 'Kidnapping or maiming a minor for purposes of begging', 'Y')
INSERT INTO ipc VALUES ('364', 'Kidnapping or abducting in order to murder', 'Y')
INSERT INTO ipc VALUES ('364A', 'Kidnapping for ransom, etc', 'Y')
INSERT INTO ipc VALUES ('365', 'Kidnapping or abducting with intent secretly and wrongfully to confine person', 'Y')
INSERT INTO ipc VALUES ('366', 'Kidnapping, abducting or inducing woman to compel her marriage,  etc', 'Y')
INSERT INTO ipc VALUES ('366A', 'Procuration of minor girl', 'Y')
INSERT INTO ipc VALUES ('366B', 'Importation of girl from foreign country', 'Y')
INSERT INTO ipc VALUES ('367', 'Kidnapping or abducting in order to subject person to grievous hurt, slavery, etc', 'Y')
INSERT INTO ipc VALUES ('368', 'Wrongfully concealing or keeping in confinement, kidnapped or abducted person', 'Y')
INSERT INTO ipc VALUES ('369', 'Kidnapping or abducting child under ten years with intent to steal from its person', 'Y')
INSERT INTO ipc VALUES ('370', 'Buying or disposing of any person as a slave', 'Y')
INSERT INTO ipc VALUES ('371', 'Habitual dealing in slaves', 'Y')
INSERT INTO ipc VALUES ('372', 'Selling minor for purposes of prostitution, etc', 'Y')
INSERT INTO ipc VALUES ('373', 'Buying minor for purposes of prostitution, etc', 'Y')
INSERT INTO ipc VALUES ('374', 'Unlawful compulsory labor', 'Y')
INSERT INTO ipc VALUES ('375', 'Rape', 'Y')
INSERT INTO ipc VALUES ('376', 'Punishment for rape', 'Y')
INSERT INTO ipc VALUES ('376A', 'Intercourse by a man with his wife during separation', 'Y')
INSERT INTO ipc VALUES ('376B', 'Intercourse by public servant with woman in his custody', 'Y')
INSERT INTO ipc VALUES ('376C', 'Intercourse by superintendent of jail, remand home, etc', 'Y')
INSERT INTO ipc VALUES ('376D', 'Intercourse by any member of the management or staff of a hospital with any woman in that hospital', 'Y')
INSERT INTO ipc VALUES ('377', 'Unnatural offences', 'Y')
INSERT INTO ipc VALUES ('Chapter XVII', 'Of Offences Against Property', 'N')
INSERT INTO ipc VALUES ('378', 'Theft', 'Y')
INSERT INTO ipc VALUES ('379', 'Punishment for theft', 'Y')
INSERT INTO ipc VALUES ('380', 'Theft in dwelling house, etc', 'Y')
INSERT INTO ipc VALUES ('381', 'Theft by clerk or servant of property in possession of master', 'Y')
INSERT INTO ipc VALUES ('382', 'Theft after preparation made for causing death, hurt or restraint in order to the committing of the theft', 'Y')
INSERT INTO ipc VALUES ('383', 'Extortion', 'Y')
INSERT INTO ipc VALUES ('384', 'Punishment for extortion', 'Y')
INSERT INTO ipc VALUES ('385', 'Putting person in fear of injury in order to commit extortion', 'Y')
INSERT INTO ipc VALUES ('386', 'Extortion by putting a person in fear of death or grievous hurt to', 'Y')
INSERT INTO ipc VALUES ('387', 'Putting person in fear of death or of grievous hurt, in order to commit extortion', 'Y')
INSERT INTO ipc VALUES ('388', 'Extortion by threat of accusation of an offence punishable with death or imprisonment for life, etc', 'Y')
INSERT INTO ipc VALUES ('389', 'Putting person in fear of accusation of offence, in order to commit extortion', 'Y')
INSERT INTO ipc VALUES ('390', 'Robbery', 'Y')
INSERT INTO ipc VALUES ('391', 'Dacoity', 'Y')
INSERT INTO ipc VALUES ('392', 'Punishment for robbery', 'Y')
INSERT INTO ipc VALUES ('393', 'Attempt to commit robbery', 'Y')
INSERT INTO ipc VALUES ('394', 'Voluntarily causing hurt in committing robbery', 'Y')
INSERT INTO ipc VALUES ('395', 'Punishment for dacoity', 'Y')
INSERT INTO ipc VALUES ('396', 'Dacoity with murder', 'Y')
INSERT INTO ipc VALUES ('397', 'Robbery, or dacoity, with attempt to cause death or grievous hurt', 'Y')
INSERT INTO ipc VALUES ('398', 'Attempt to commit robbery or dacoity when armed with deadly weapon', 'Y')
INSERT INTO ipc VALUES ('399', 'Making preparation to commit dacoity', 'Y')
INSERT INTO ipc VALUES ('400', 'Punishment for belonging to gang of dacoits', 'Y')
INSERT INTO ipc VALUES ('401', 'Punishment for belonging to gang of thieves', 'Y')
INSERT INTO ipc VALUES ('402', 'Assembling for purpose of committing dacoity', 'Y')
INSERT INTO ipc VALUES ('403', 'Dishonest misappropriation of property', 'Y')
INSERT INTO ipc VALUES ('404', 'Dishonest misappropriation of property possessed by deceased person at the time of his death', 'Y')
INSERT INTO ipc VALUES ('405', 'Criminal breach of trust', 'Y')
INSERT INTO ipc VALUES ('406', 'Punishment for criminal breach of trust', 'Y')
INSERT INTO ipc VALUES ('407', 'Criminal breach of trust by carrier, etc', 'Y')
INSERT INTO ipc VALUES ('408', 'Criminal breach of trust by clerk or servant', 'Y')
INSERT INTO ipc VALUES ('409', 'Criminal breach of trust by public servant, or by banker, merchant or agent', 'Y')
INSERT INTO ipc VALUES ('410', 'Stolen Property', 'Y')
INSERT INTO ipc VALUES ('411', 'Dishonestly receiving stolen property', 'Y')
INSERT INTO ipc VALUES ('412', 'Dishonestly receiving property stolen in the commission of a dacoity', 'Y')
INSERT INTO ipc VALUES ('413', 'Habitually dealing in stolen property', 'Y')
INSERT INTO ipc VALUES ('414', 'Assisting in concealment of stolen property', 'Y')
INSERT INTO ipc VALUES ('415', 'Cheating', 'Y')
INSERT INTO ipc VALUES ('416', 'Cheating by personation', 'Y')
INSERT INTO ipc VALUES ('417', 'Punishment for cheating', 'Y')
INSERT INTO ipc VALUES ('418', 'Cheating with knowledge that wrongful loss may ensue to person whose interest offender is bound to protect', 'Y')
INSERT INTO ipc VALUES ('419', 'Punishment for cheating by personation', 'Y')
INSERT INTO ipc VALUES ('420', 'Cheating and dishonestly inducing delivery of property', 'Y')
INSERT INTO ipc VALUES ('421', 'Dishonest or fraudulent removal or concealment of property to prevent distribution among creditors', 'Y')
INSERT INTO ipc VALUES ('422', 'Dishonestly or fraudulently preventing debt being available for creditors-.', 'Y')
INSERT INTO ipc VALUES ('423', 'Dishonest or fraudulent execution of deed of transfer containing false statement of consideration', 'Y')
INSERT INTO ipc VALUES ('424', 'Dishonest or fraudulent removal or concealment of property', 'Y')
INSERT INTO ipc VALUES ('425', 'Mischief', 'Y')
INSERT INTO ipc VALUES ('426', 'Punishment for mischief-', 'Y')
INSERT INTO ipc VALUES ('427', 'Mischief causing damage to the amount of fifty rupees', 'Y')
INSERT INTO ipc VALUES ('428', 'Mischief by killing or maiming animal of the value of ten rupees.', 'Y')
INSERT INTO ipc VALUES ('429', 'Mischief by killing or maiming cattle, etc., of any value or any animal of the value of fifty rupees', 'Y')
INSERT INTO ipc VALUES ('430', 'Mischief by injury to works of irrigation or by wrongfully diverting water', 'Y')
INSERT INTO ipc VALUES ('431', 'Mischief by injury to public road, bridge, river or channel', 'Y')
INSERT INTO ipc VALUES ('432', 'Mischief by causing inundation or obstruction to public drainage attended with damage', 'Y')
INSERT INTO ipc VALUES ('433', 'Mischief by destroying, moving or rendering less useful a light-house or sea-mark', 'Y')
INSERT INTO ipc VALUES ('434', 'Mischief by destroying or moving, etc., a land-mark fixed by public authority', 'Y')
INSERT INTO ipc VALUES ('435', 'Mischief by fire or explosive substance with intent to cause damage to amount of one hundred or (in case of agricultural produce) ten rupees', 'Y')
INSERT INTO ipc VALUES ('436', 'Mischief by fire or explosive substance with intent to destroy house, etc', 'Y')
INSERT INTO ipc VALUES ('437', 'Mischief with intent to destroy or make unsafe a decked vessel or one of twenty tons burden', 'Y')
INSERT INTO ipc VALUES ('438', 'Punishment for the mischief described in section 437 committed by fire or explosive substance', 'Y')
INSERT INTO ipc VALUES ('439', 'Punishment for intentionally running vessel aground or ashore with intent to commit theft, etc', 'Y')
INSERT INTO ipc VALUES ('440', 'Mischief committed after preparation made for causing death or hurt', 'Y')
INSERT INTO ipc VALUES ('441', 'Criminal trespass', 'Y')
INSERT INTO ipc VALUES ('442', 'House trespass', 'Y')
INSERT INTO ipc VALUES ('443', 'Lurking house-trespass', 'Y')
INSERT INTO ipc VALUES ('444', 'Lurking house-trespass by night', 'Y')
INSERT INTO ipc VALUES ('445', 'House breaking', 'Y')
INSERT INTO ipc VALUES ('446', 'House-breaking by night', 'Y')
INSERT INTO ipc VALUES ('447', 'Punishment for criminal trespass', 'Y')
INSERT INTO ipc VALUES ('448', 'Punishment for house-trespass', 'Y')
INSERT INTO ipc VALUES ('449', 'House-trespass in order to commit offence punishable with death', 'Y')
INSERT INTO ipc VALUES ('450', 'House-trespass in order to commit offence punishable with imprisonment for life', 'Y')
INSERT INTO ipc VALUES ('451', 'House-trespass in order to commit offence punishable with imprisonment', 'Y')
INSERT INTO ipc VALUES ('452', 'House-trespass after preparation for hurt, assault or wrongful restraint', 'Y')
INSERT INTO ipc VALUES ('453', 'Punishment for lurking house-trespass or house-breaking', 'Y')
INSERT INTO ipc VALUES ('454', 'Lurking house-trespass or house-breaking in order to commit offence punishable with imprisonment', 'Y')
INSERT INTO ipc VALUES ('455', 'Lurking house-trespass or house-breaking after preparation for hurt, assault or wrongful restraint', 'Y')
INSERT INTO ipc VALUES ('456', 'Punishment for lurking house-trespass or house-breaking by night', 'Y')
INSERT INTO ipc VALUES ('457', 'Lurking house-trespass or house-breaking by night in order to commit offence punishable with imprisonment', 'Y')
INSERT INTO ipc VALUES ('458', 'Lurking house-trespass or house-breaking by night after preparation for hurt, assault, or wrongful restraint', 'Y')
INSERT INTO ipc VALUES ('459', 'Grievous hurt caused whilst committing lurking house trespass or housebreaking', 'Y')
INSERT INTO ipc VALUES ('460', 'All persons jointly concerned in lurking house-trespass or house-breaking by night punishable where death or grievous hurt caused by one of them', 'Y')
INSERT INTO ipc VALUES ('461', 'Dishonestly breaking open receptacle containing property', 'Y')
INSERT INTO ipc VALUES ('462', 'Punishment for same offence when committed by person entrusted with custody', 'Y')
INSERT INTO ipc VALUES ('Chapter XVIII ', 'Of Offences Relating To Documents And To 173[***] Property Marks', 'N')
INSERT INTO ipc VALUES ('463', 'Forgery', 'Y')
INSERT INTO ipc VALUES ('464', 'Making a false document', 'Y')
INSERT INTO ipc VALUES ('465', 'Punishment for forgery', 'Y')
INSERT INTO ipc VALUES ('466', 'Forgery of record of court or of public register, etc', 'Y')
INSERT INTO ipc VALUES ('467', 'Forgery of valuable security, will, etc', 'Y')
INSERT INTO ipc VALUES ('468', 'Forgery for purpose of cheating', 'Y')
INSERT INTO ipc VALUES ('469', 'Forgery for purpose of harming reputation', 'Y')
INSERT INTO ipc VALUES ('470', 'Forged document', 'Y')
INSERT INTO ipc VALUES ('471', 'Using as genuine a forged document', 'Y')
INSERT INTO ipc VALUES ('472', 'Making or possessing counterfeit seal, etc., with intent to commit forgery punishable under section 467', 'Y')
INSERT INTO ipc VALUES ('473', 'Making or possessing counterfeit seal, etc., with intent to commit forgery punishable otherwise', 'Y')
INSERT INTO ipc VALUES ('474', 'Having possession of document described in section 466 or 467, knowing it to be forged and intending to use it as genuine', 'Y')
INSERT INTO ipc VALUES ('475', 'Counterfeiting device or mark used for authenticating documents described in section 467, or possessing counterfeit marked material', 'Y')
INSERT INTO ipc VALUES ('476', 'Counterfeiting device or mark used for authenticating documents other than those described in section 467, or possessing counterfeit marked material', 'Y')
INSERT INTO ipc VALUES ('477', 'Fraudulent cancellation, destruction, etc., of will, authority to adopt, or valuable security', 'Y')
INSERT INTO ipc VALUES ('477A', 'Falsification of accounts', 'Y')
INSERT INTO ipc VALUES ('478', '[Trade marks Repealed by the Trade and Merchandise Marks Act, 1958, w.e.f. 25th. November, 1959]', 'N')
INSERT INTO ipc VALUES ('479', 'Property mark', 'Y')
INSERT INTO ipc VALUES ('480', 'Using a false trade mark: Repealed by the Trade and Merchandise Marks Act, 1958, w.e.f. 25th. November, 1959', 'Y')
INSERT INTO ipc VALUES ('481', 'Using a false property mark', 'Y')
INSERT INTO ipc VALUES ('482', 'Punishment for using a false property mark', 'Y')
INSERT INTO ipc VALUES ('483', 'Counterfeiting a property mark used by another', 'Y')
INSERT INTO ipc VALUES ('484', 'Counterfeiting a mark used by a public servant', 'Y')
INSERT INTO ipc VALUES ('485', 'Making or possession of any instrument for counterfeiting a property mark', 'Y')
INSERT INTO ipc VALUES ('486', 'Selling goods marked with a counterfeit property mark', 'Y')
INSERT INTO ipc VALUES ('487', 'Making a false mark upon any receptacle containing goods', 'Y')
INSERT INTO ipc VALUES ('488', 'Punishment for making use of any such false mark', 'Y')
INSERT INTO ipc VALUES ('489', 'Tampering with property mark with intent to cause injury', 'Y')
INSERT INTO ipc VALUES ('489A', 'Counterfeiting currency-notes or bank-notes', 'Y')
INSERT INTO ipc VALUES ('489B', 'Using as genuine, forged or counterfeit currency-notes or bank- notes', 'Y')
INSERT INTO ipc VALUES ('489C', 'Possession of forged or counterfeit currency-notes or bank-notes', 'Y')
INSERT INTO ipc VALUES ('489D', 'Making or possessing instruments or materials for forging or counterfeiting currency-notes or bank-notes', 'Y')
INSERT INTO ipc VALUES ('489E', 'Making or using documents resembling currency-notes or bank-notes', 'Y')
INSERT INTO ipc VALUES ('Chapter XIX', 'Of The Criminal Breach Of Contracts Of Service', 'N')
INSERT INTO ipc VALUES ('490', '[Breach of contract of service during voyage or journey: Repealed by the Workmen''s Breach of Contract (Repealing) Act, 1925]', 'N')
INSERT INTO ipc VALUES ('491', 'Breach of contract to attend on and supply wants of helpless person', 'Y')
INSERT INTO ipc VALUES ('492', '[Breach of contract to serve at distant place to which servant is conveyed at master''s expense: Repealed by the Workmen''s Breach of Contract (Repealing) Act, 1925 (3 of 1925)]', 'N')
INSERT INTO ipc VALUES ('Chapter XX', 'Of Offences Relating To Marriage', 'N')
INSERT INTO ipc VALUES ('493', 'Cohabitation caused by a man deceitfully inducing a belief of lawful marriage', 'Y')
INSERT INTO ipc VALUES ('494', 'Marrying again during lifetime of husband or wife', 'Y')
INSERT INTO ipc VALUES ('495', 'Same offence with concealment of former marriage from person with whom subsequent marriage is contracted', 'Y')
INSERT INTO ipc VALUES ('496', 'Marriage ceremony fraudulently gone through without lawful marriage', 'Y')
INSERT INTO ipc VALUES ('497', 'Adultery', 'Y')
INSERT INTO ipc VALUES ('498', 'Enticing or taking away or detaining with criminal intent a married woman', 'Y')
INSERT INTO ipc VALUES ('Chapter XXA', 'Of Cruelty By Husband Or Relatives Of Husband', 'N')
INSERT INTO ipc VALUES ('498A', 'Husband or relative of husband of a woman subjecting her to cruelty', 'Y')
INSERT INTO ipc VALUES ('Chapter XXI', 'Of Defamation', 'N')
INSERT INTO ipc VALUES ('499', 'Defamation', 'Y')
INSERT INTO ipc VALUES ('500', 'Punishment for defamation', 'Y')
INSERT INTO ipc VALUES ('501', 'Printing or engraving matter known to be defamatory', 'Y')
INSERT INTO ipc VALUES ('502s', 'Sale of printed or engraved substance containing defamatory matter', 'Y')
INSERT INTO ipc VALUES ('Chapter XXII', 'Of Criminal Intimidation, Insult And Annoyance', 'N')
INSERT INTO ipc VALUES ('503', 'Criminal intimidation', 'Y')
INSERT INTO ipc VALUES ('504', 'Intentional insult with intent to provoke breach of the peace', 'Y')
INSERT INTO ipc VALUES ('505', 'Statements conducting to public mischief.', 'Y')
INSERT INTO ipc VALUES ('506', 'Punishment for criminal intimidation', 'Y')
INSERT INTO ipc VALUES ('507', 'Criminal intimidation by an anonymous communication', 'Y')
INSERT INTO ipc VALUES ('508', 'Act caused by inducing person to believe that he will be rendered an object of the Divine displeasure', 'Y')
INSERT INTO ipc VALUES ('509', 'Word, gesture or act intended to insult the modesty of a woman', 'Y')
INSERT INTO ipc VALUES ('510', 'Misconduct in public by a drunken person', 'Y')
INSERT INTO ipc VALUES ('Chapter XXIII', 'Of Attempts To Commit Offences', 'N')
INSERT INTO ipc VALUES ('511', 'Punishment for attempting to commit offences punishable with imprisonment for life or other imprisonment', 'Y')