INSERT INTO post_office_t VALUES('Aibawk', 796190, 'Sub Office(Delivery)', '', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2578377');
INSERT INTO post_office_t VALUES('Aiduzawl', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Aizawl', 796001, 'Head Office(Delivery)', '', '', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2328023');
INSERT INTO post_office_t VALUES('Armed Veng', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Armed Veng', 796008, 'Sub Office(Delivery)', '', 'Aizawl', 'Tlangnuam Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '-');
INSERT INTO post_office_t VALUES('Baktawng', 796161, 'Branch Office(Delivery)', 'Thingsulthliah', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bawngkawn', 796014, 'Sub Office(Delivery)', '', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2346115');
INSERT INTO post_office_t VALUES('Bethlehem', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Buhban', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bukpui', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Chandmary Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bungkawn', 796005, 'Branch Office(Non Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chaltlang', 796012, 'Branch Office(Non Delivery)', 'Ramhlun', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chandmary', 796007, 'Sub Office(Delivery)', '', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2341204');
INSERT INTO post_office_t VALUES('Changzawl', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chawlhhmun', 796009, 'Branch Office(Delivery)', 'Vaivakawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chhingchhip', 796161, 'Branch Office(Delivery)', 'Thingsulthliah', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('College Veng', 796005, 'Branch Office(Non Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Cti Sesawng', 796017, 'Branch Office(Delivery)', 'Zemabawk', 'Aizawl', 'Thingsulthliah (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Daido', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Darlawn', 796111, 'Sub Office(Delivery)', '', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2569338');
INSERT INTO post_office_t VALUES('Dawrpui', 796001, 'Sub Office(Non Delivery)', '', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2317488');
INSERT INTO post_office_t VALUES('Dinthar', 796009, 'Branch Office(Non Delivery)', 'Vaivakawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Durtlang', 796025, 'Sub Office(Delivery)', '', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2361197');
INSERT INTO post_office_t VALUES('Electric Veng', 796007, 'Branch Office(Non Delivery)', 'Chandmary', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Govt. Complex', 796009, 'Branch Office(Delivery)', 'Vaivakawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hmuifang', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hmuntha', 796161, 'Branch Office(Delivery)', 'Thingsulthliah', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hriphaw', 796471, 'Branch Office(Delivery)', 'Zawlnuam', 'Aizawl', 'Zawlnuam Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hualngohmun', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hualtu', 796161, 'Branch Office(Delivery)', 'Thingsulthliah', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Keifang', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Phullen Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kelsih', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Kulikawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kepran', 796017, 'Branch Office(Delivery)', 'Zemabawk', 'Aizawl', 'Zemabawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khanpui', 796017, 'Branch Office(Delivery)', 'Zemabawk', 'Aizawl', 'Zemabawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawbel', 796161, 'Branch Office(Delivery)', 'Thingsulthliah', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawchhete', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Kulikawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawlian', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawpuar', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawruhlian', 796017, 'Branch Office(Delivery)', 'Zemabawk', 'Aizawl', 'Zemabawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khumtung', 796161, 'Branch Office(Delivery)', 'Thingsulthliah', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kulikawn', 796005, 'Sub Office(Delivery)', '', 'Aizawl', 'Kulikawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2322866');
INSERT INTO post_office_t VALUES('Lamchhip', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lengpui Airport', 796421, 'Sub Office(Delivery)', '', 'Aizawl', 'Lengpui Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2573380');
INSERT INTO post_office_t VALUES('Lengpui', 796410, 'Branch Office(Delivery)', 'Sairang', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Luangmual', 796009, 'Branch Office(Delivery)', 'Vaivakawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Luangpawn', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungdai', 796014, 'Branch Office(Delivery)', 'Bawngkawn', 'Aizawl', 'Bawngkawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungmuat', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Chandmary Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungpher ''N''', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungsum', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lushaicherra', 796471, 'Branch Office(Delivery)', 'Zawlnuam', 'Aizawl', 'Zawlnuam Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Maite', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Maubawk', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Maubuang', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mauchar', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Missionvengthlang', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mizoram University', 796004, 'Sub Office(Delivery)', '', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '-');
INSERT INTO post_office_t VALUES('Muallungthu', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Kulikawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mualmawi', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mualpheng', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mualpui', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Muthi', 796014, 'Branch Office(Delivery)', 'Bawngkawn', 'Aizawl', 'Bawngkawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Chaltlang', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Chandmary Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.E.Bualpui', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Phullen Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Hlimen', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Chandmary Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Khawlek', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Lungleng', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Kulikawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Serzawl', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Tinghmun', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('New Vervek', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Nisapui', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Chanmary Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Palsang', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Pawlrang', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Phaileng ''E''', 796017, 'Branch Office(Delivery)', 'Zemabawk', 'Aizawl', 'Zemabawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Phuaibuang', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Phullen', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Phulpui', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ptc Lungverh', 796410, 'Branch Office(Delivery)', 'Sairang', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ramhlun', 796012, 'Sub Office(Delivery)', '', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2341081');
INSERT INTO post_office_t VALUES('Ramthar', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Rangvamual', 796009, 'Branch Office(Delivery)', 'Vaivakawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ratu', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Republic Veng', 796005, 'Branch Office(Non Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ruallung', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Phullen Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('S,hlimen', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sabualkawn', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Saichal', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sailam', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sailutar', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Saitual', 796261, 'Sub Office(Delivery)', '', 'Aizawl', 'Phullen Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2562299');
INSERT INTO post_office_t VALUES('Sakawrdai', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sakawrtuichhun', 796009, 'Branch Office(Delivery)', 'Vaivakawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Samlukhai', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sateek', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sawleng', 796017, 'Branch Office(Delivery)', 'Zemabawk', 'Aizawl', 'Zemabawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Selesih', 796014, 'Branch Office(Delivery)', 'Bawngkawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Seling', 796161, 'Branch Office(Delivery)', 'Thingsulthliah', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Serkhan', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Chandmary Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sesawng', 796017, 'Branch Office(Delivery)', 'Zemabawk', 'Aizawl', 'Zemabawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sialsuk', 796230, 'Sub Office(Delivery)', '', 'Aizawl', 'Sialsuk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2571212');
INSERT INTO post_office_t VALUES('Sihfa', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sihphir', 796036, 'Sub Office(Delivery)', '', 'Aizawl', 'Sihphir Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2364239');
INSERT INTO post_office_t VALUES('Suangpuilawn', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sumsuih', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tachhip', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tanhril', 796009, 'Branch Office(Delivery)', 'Vaivakawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thakthingbazar', 796005, 'Branch Office(Non Delivery)', 'Kulikawn', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thentlang', 796161, 'Branch Office(Delivery)', 'Thingsulthliah', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thiak', 796190, 'Branch Office(Delivery)', 'Aibawk', 'Aizawl', 'Aibawk Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thingdawlmelriat', 796005, 'Branch Office(Delivery)', 'Kulikawn', 'Aizawl', 'Kulikawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thingsat', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thingsulthliah', 796161, 'Sub Office(Delivery)', '', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2370422');
INSERT INTO post_office_t VALUES('Thingthelh', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Chandmary Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tlangnuam', 796015, 'Sub Office(Delivery)', '', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2310904');
INSERT INTO post_office_t VALUES('Tlungvel', 796161, 'Branch Office(Delivery)', 'Thingsulthliah', 'Aizawl', 'Thingsulthliah Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tualbung', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuirial H.E.P', 796101, 'Branch Office(Delivery)', 'Vairengte', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuithiang', 796007, 'Branch Office(Delivery)', 'Chandmary', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vaitin', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vaivakawn', 796009, 'Sub Office(Delivery)', '', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2340050');
INSERT INTO post_office_t VALUES('Vanbawng', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vervek', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zamuang', 796471, 'Branch Office(Delivery)', 'Zawlnuam', 'Aizawl', 'Zawlnuam Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zanlawn', 796014, 'Branch Office(Delivery)', 'Bawngkawn', 'Aizawl', 'Bawngkawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zawlnuam', 796471, 'Sub Office(Delivery)', '', 'Aizawl', 'Zawlnuam Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-269291');
INSERT INTO post_office_t VALUES('Zawngin', 796261, 'Branch Office(Delivery)', 'Saitual', 'Aizawl', 'Saitual Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zemabawk', 796017, 'Sub Office(Delivery)', '', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '0389-2350930');
INSERT INTO post_office_t VALUES('Zohmun', 796111, 'Branch Office(Delivery)', 'Darlawn', 'Aizawl', 'Darlawn Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zuangtui', 796017, 'Branch Office(Delivery)', 'Zemabawk', 'Aizawl', 'Tlangnuam (Part) Taluk of Aizawl District', 'Aizawl ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bethel', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Biate', 796370, 'Branch Office(Delivery)', 'Lungdar', 'Aizawl', 'East Lungdar (Part) Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bungzung', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chalrang', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Champhai', 796321, 'Sub Office(Delivery)', '', 'Aizawl', 'Khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '03831-234323');
INSERT INTO post_office_t VALUES('Chawngtlai', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chhawkhlei', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chhawrtui', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Dulte', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Dungtlang', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Farkawn', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hmunhmeltha', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hnahlan', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hrianghmun', 796290, 'Branch Office(Delivery)', 'Ngopa', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hruaikawn', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kawlbem', 796290, 'Branch Office(Delivery)', 'Ngopa', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kawlkulh', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kelkang', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawhai', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawkawn', 796290, 'Branch Office(Delivery)', 'Ngopa', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawnuam', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawzawl', 796310, 'Sub Office(Delivery)', '', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '03831-261006');
INSERT INTO post_office_t VALUES('Khuangleng', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khuangphah', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khuangthing', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lamzawl', 796290, 'Branch Office(Delivery)', 'Ngopa', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Leisenzo', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Leithum', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungphunlian', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungtan', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Maulkawi', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mimbung', 796290, 'Branch Office(Delivery)', 'Ngopa', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mualcheng', 796370, 'Branch Office(Delivery)', 'Lungdar', 'Aizawl', 'East Lungdar (Part) Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Muallung', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Murlen', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Chalrang', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Khawbung', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ne Khawdungsei', 796290, 'Branch Office(Delivery)', 'Ngopa', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Neihdawn', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ngopa', 796290, 'Sub Office(Delivery)', '', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '03830-261491');
INSERT INTO post_office_t VALUES('Ngur', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Puilo', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Riangtlei', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ruantlang', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Rullam', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('S.Khawbung', 796320, 'Sub Office(Delivery)', '', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '03831-265282');
INSERT INTO post_office_t VALUES('Samthang', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sazep', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Selam', 796290, 'Branch Office(Delivery)', 'Ngopa', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sesih', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Teikhang', 796290, 'Branch Office(Delivery)', 'Ngopa', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tlangsam', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tualcheng', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tualpui', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tualte', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vaikhawtlang', 796290, 'Branch Office(Delivery)', 'Ngopa', 'Aizawl', 'Ngopa Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vanchengpui', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vangchhia', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vangtlang', 796310, 'Branch Office(Delivery)', 'Khawzawl', 'Aizawl', 'Khawzawl Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vanzau', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vapar', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Champhai Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vaphai', 796320, 'Branch Office(Delivery)', 'S.Khawbung', 'Aizawl', 'S.khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vengthlang', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zote ''e''', 796321, 'Branch Office(Delivery)', 'Champhai', 'Aizawl', 'Khawbung Taluk of Champhai District', 'Champhai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bairabi', 796081, 'Branch Office(Delivery)', 'Kolasib', 'Aizawl', 'North Thingdawl Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bilkhawthlir', 796091, 'Sub Office(Delivery)', '', 'Aizawl', 'Bilkhawthlir Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '03837-265187');
INSERT INTO post_office_t VALUES('Bualpui', 796070, 'Branch Office(Delivery)', 'Kawnpui', 'Aizawl', 'North Thingdawl Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Buhchang', 796091, 'Branch Office(Delivery)', 'Bilkhawthlir', 'Aizawl', 'Bilkhawthlir Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Builum', 796081, 'Branch Office(Delivery)', 'Kolasib', 'Aizawl', 'Kolasib Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chuhvel', 796081, 'Branch Office(Delivery)', 'Kolasib', 'Aizawl', 'Kolasib Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Diakkawn', 796081, 'Branch Office(Delivery)', 'Kolasib', 'Aizawl', 'North Thingdawl Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Diakkawn', 796081, 'Branch Office(Non Delivery)', 'Kolasib', 'Aizawl', 'North Thingdawl Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Diakkawn', 796082, 'Sub Office(Delivery)', '', 'Aizawl', 'Kolasib Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '-');
INSERT INTO post_office_t VALUES('Hortoki', 796070, 'Branch Office(Delivery)', 'Kawnpui', 'Aizawl', 'Kawnpui Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kawnpui', 796070, 'Sub Office(Delivery)', '', 'Aizawl', 'North Thingdawl Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '03837-266647');
INSERT INTO post_office_t VALUES('Kolasib', 796081, 'Sub Office(Delivery)', '', 'Aizawl', 'North Thingdawl Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '03837-220030');
INSERT INTO post_office_t VALUES('Mualvum', 796070, 'Branch Office(Delivery)', 'Kawnpui', 'Aizawl', 'Kawnpui Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Chawnpui', 796101, 'Branch Office(Delivery)', 'Vairengte', 'Aizawl', 'Vairengte Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Phainuam', 796101, 'Branch Office(Delivery)', 'Vairengte', 'Aizawl', 'Vairengte Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Phaisen', 796091, 'Branch Office(Delivery)', 'Bilkhawthlir', 'Aizawl', 'Bilkhawthlir Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Saihapui ''K''', 796081, 'Branch Office(Delivery)', 'Kolasib', 'Aizawl', 'Kolasib Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Saikhawthlir', 796081, 'Branch Office(Delivery)', 'Kolasib', 'Aizawl', 'Kolasib Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Saiphai', 796101, 'Branch Office(Delivery)', 'Vairengte', 'Aizawl', 'Vairengte Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Saipum', 796101, 'Branch Office(Delivery)', 'Vairengte', 'Aizawl', 'Vairengte Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Suarhliap', 796081, 'Branch Office(Delivery)', 'Kolasib', 'Aizawl', 'Kolasib Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thingdawl', 796075, 'Sub Office(Delivery)', '', 'Aizawl', 'North Thingdawl Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '03837-268525');
INSERT INTO post_office_t VALUES('Vairengte', 796101, 'Sub Office(Delivery)', '', 'Aizawl', 'North Thingdawl Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '03837-261079');
INSERT INTO post_office_t VALUES('Vengthar', 796081, 'Branch Office(Delivery)', 'Kolasib', 'Aizawl', 'North Thingdawl Taluk of Kolasib District', 'Kolasib ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Balhlakawn', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bungtlang ''S''', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chamdur', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Cheural', 796810, 'Branch Office(Delivery)', 'Sangau', 'Aizawl', 'Sangau Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Diltlang', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kamalanagar (Lawngtlai)', 796772, 'Sub Office(Delivery)', '', 'Aizawl', 'Chawngte Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '0372-2563800');
INSERT INTO post_office_t VALUES('Karlui', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kawlchaw ''W''', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lawngtlai', 796891, 'Sub Office(Delivery)', '', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '03835-232244');
INSERT INTO post_office_t VALUES('Lungtian', 796810, 'Branch Office(Delivery)', 'Sangau', 'Aizawl', 'Sangau Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mampui', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mualbukawn', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('New Jagnasury', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ngengpuikai', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Paithar', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Pangkhua', 796810, 'Branch Office(Delivery)', 'Sangau', 'Aizawl', 'Sangau Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Parva', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Rulkual', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sabualtlang', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Saizawh', 796770, 'Branch Office(Delivery)', 'Chawngte', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sangau', 796810, 'Sub Office(Delivery)', '', 'Aizawl', 'Sangau Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '0372-2553184');
INSERT INTO post_office_t VALUES('Tuisentlang', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuithumhnar', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Udaisury', 796770, 'Branch Office(Delivery)', 'Chawngte', 'Aizawl', 'Chawngte Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Udalthana', 796770, 'Branch Office(Delivery)', 'Chawngte', 'Aizawl', 'Chawngte Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vaseitlang', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vathuampui', 796891, 'Branch Office(Delivery)', 'Lawngtlai', 'Aizawl', 'Lawngtlai Taluk of Lawngtlai District', 'Lawngtlai ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Aithur', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ajasora', 796770, 'Branch Office(Delivery)', 'Chawngte', 'Aizawl', 'Chawngte Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Belthei', 796730, 'Branch Office(Delivery)', 'Lungsen', 'Aizawl', 'Lungsen Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Borapansury', 796770, 'Branch Office(Delivery)', 'Chawngte', 'Aizawl', 'Chawngte Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bualpui H', 796581, 'Branch Office(Delivery)', 'Thingsai', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bualte', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Buarpui', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bunghmun', 796710, 'Sub Office(Delivery)', '', 'Aizawl', 'West Bunghmun Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '0372-2565092');
INSERT INTO post_office_t VALUES('Chandmary', 796701, 'Branch Office(Non Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Changpui', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chawngte', 796770, 'Sub Office(Delivery)', '', 'Aizawl', 'Chawngte Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '0372-2563251');
INSERT INTO post_office_t VALUES('Chawngtui', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Cherhlun', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hanhthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Darngawn ''W''', 796710, 'Branch Office(Delivery)', 'Bunghmun', 'Aizawl', 'West Bunghmun Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Darzo', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Demagiri', 796751, 'Sub Office(Delivery)', '', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '03834-222031');
INSERT INTO post_office_t VALUES('Diblibagh', 796751, 'Branch Office(Delivery)', 'Demagiri', 'Aizawl', 'Demagiri Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Haulawng', 796691, 'Branch Office(Delivery)', 'Zotlang', 'Aizawl', 'Zotlang Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hauruang', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hnahchang', 796691, 'Branch Office(Delivery)', 'Zotlang', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hnahthial', 796571, 'Sub Office(Delivery)', '', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '0372-2332101');
INSERT INTO post_office_t VALUES('Hrangchalkawn', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Jarulsury', 796770, 'Branch Office(Delivery)', 'Chawngte', 'Aizawl', 'Chawngte Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kajoisury', 796751, 'Branch Office(Delivery)', 'Demagiri', 'Aizawl', 'Demagiri Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kawnpui ''W''', 796710, 'Branch Office(Delivery)', 'Bunghmun', 'Aizawl', 'Bunghmun Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kikawn', 796701, 'Branch Office(Non Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Laisawral', 796710, 'Branch Office(Delivery)', 'Bunghmun', 'Aizawl', 'Bunghmun Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Leite', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungchem', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lunglawn', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lunglei', 796701, 'Sub Office(Delivery)', '', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '0372-2324035');
INSERT INTO post_office_t VALUES('Lungleng ''s''', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungrang ''S''', 796730, 'Branch Office(Delivery)', 'Lungsen', 'Aizawl', 'Lungsen Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungsen', 796730, 'Sub Office(Delivery)', '', 'Aizawl', 'Lungsen Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '03834-261016');
INSERT INTO post_office_t VALUES('Mualcheng ''S''', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Muallianpui', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mualthuam ''N''', 796691, 'Branch Office(Delivery)', 'Zotlang', 'Aizawl', 'Zotlang Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Nunsury', 796751, 'Branch Office(Delivery)', 'Demagiri', 'Aizawl', 'Demagiri Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Pangzawl', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Phairuangkai', 796730, 'Branch Office(Delivery)', 'Lungsen', 'Aizawl', 'Lungsen Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Puankhai', 796751, 'Branch Office(Delivery)', 'Demagiri', 'Aizawl', 'Demagiri Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Pukpui', 796691, 'Branch Office(Delivery)', 'Zotlang', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Putlungasih', 796730, 'Branch Office(Delivery)', 'Lungsen', 'Aizawl', 'Lungsen Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ralvawng', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Ramlaitui', 796691, 'Branch Office(Delivery)', 'Zotlang', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Rangte', 796730, 'Branch Office(Delivery)', 'Lungsen', 'Aizawl', 'Lungsen Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Rawpui', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Rualalung', 796730, 'Branch Office(Delivery)', 'Lungsen', 'Aizawl', 'Lungsen Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('S.Chawilung', 796751, 'Branch Office(Delivery)', 'Demagiri', 'Aizawl', 'Demagiri Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('S.Vanlaiphai', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sachan', 796710, 'Branch Office(Delivery)', 'Bunghmun', 'Aizawl', 'Bunghmun Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sazaikawn', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Serkawn', 796691, 'Branch Office(Delivery)', 'Zotlang', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sertlangpui', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sesawm', 796710, 'Branch Office(Delivery)', 'Bunghmun', 'Aizawl', 'Bunghmun Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sumsilui', 796770, 'Branch Office(Delivery)', 'Chawngte', 'Aizawl', 'Chawngte Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tarpho', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tawipui ''N''', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tawipui ''S''', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Theiriat', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thenhlum', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thiltlang', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thingfal', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thingsai', 796581, 'Sub Office(Delivery)', '', 'Aizawl', 'Thingsai Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '-');
INSERT INTO post_office_t VALUES('Thualthu', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thuampui', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tiperaghat', 796751, 'Branch Office(Delivery)', 'Demagiri', 'Aizawl', 'Demagiri Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuichawng', 796730, 'Branch Office(Delivery)', 'Lungsen', 'Aizawl', 'Lungsen Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuikawi', 796751, 'Branch Office(Delivery)', 'Demagiri', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuipui ''D''', 796571, 'Branch Office(Delivery)', 'Hnahthial', 'Aizawl', 'Hnahthial Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vaisam', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vanhne', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zawlpui', 796730, 'Branch Office(Delivery)', 'Lungsen', 'Aizawl', 'Lungsen Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zobawk', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zodin', 796751, 'Branch Office(Delivery)', 'Demagiri', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zohnuai', 796701, 'Branch Office(Delivery)', 'Lunglei', 'Aizawl', 'Lunglei Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zotlang', 796691, 'Sub Office(Delivery)', '', 'Aizawl', 'Zotlang Taluk of Lunglei District', 'Lunglei ', 'Mizoram', '0372-2342280');
INSERT INTO post_office_t VALUES('Ailawng', 796501, 'Branch Office(Delivery)', 'Reiek', 'Aizawl', 'Reiek Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Boraibazar', 796471, 'Branch Office(Delivery)', 'Zawlnuam', 'Aizawl', 'Zawlnuam Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Damparengpui', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Dampui', 796441, 'Branch Office(Delivery)', 'Mamit', 'Aizawl', 'Mamit Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Dapchhuah', 796410, 'Branch Office(Delivery)', 'Sairang', 'Aizawl', 'Sairang Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Darlak', 796441, 'Branch Office(Delivery)', 'Mamit', 'Aizawl', 'Mamit Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Darlung', 796501, 'Branch Office(Delivery)', 'Reiek', 'Aizawl', 'Reiek Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hmunpui', 796410, 'Branch Office(Delivery)', 'Sairang', 'Aizawl', 'Sairang Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Hnahva', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kanghmun', 796501, 'Branch Office(Delivery)', 'Reiek', 'Aizawl', 'Reiek Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kanhmunbazar', 796471, 'Branch Office(Delivery)', 'Zawlnuam', 'Aizawl', 'Zawlnuam Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kawrtethawveng', 796441, 'Branch Office(Delivery)', 'Mamit', 'Aizawl', 'Mamit Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kawrthah', 796441, 'Branch Office(Delivery)', 'Mamit', 'Aizawl', 'Mamit Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawhnai', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawrihnim', 796501, 'Branch Office(Delivery)', 'Reiek', 'Aizawl', 'Reiek Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lallen', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungdar ''W''', 796501, 'Branch Office(Delivery)', 'Reiek', 'Aizawl', 'Reiek Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mamit', 796441, 'Sub Office(Delivery)', '', 'Aizawl', 'West Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '0372-2563251');
INSERT INTO post_office_t VALUES('Marpara', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'West Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Momcherra', 796471, 'Branch Office(Delivery)', 'Zawlnuam', 'Aizawl', 'Zawlnuam Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Mualkhang', 796410, 'Branch Office(Delivery)', 'Sairang', 'Aizawl', 'Sairang Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Chhippui', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Sabual', 796441, 'Branch Office(Delivery)', 'Mamit', 'Aizawl', 'Mamit Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Parvatui', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Phaileng', 796431, 'Sub Office(Delivery)', '', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '0389-2566400');
INSERT INTO post_office_t VALUES('Phuldungsei', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Pukzing', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Rawpuichhip', 796410, 'Branch Office(Delivery)', 'Sairang', 'Aizawl', 'Sairang Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Reiek', 796501, 'Sub Office(Delivery)', '', 'Aizawl', 'Reiek Taluk of Mammit District', 'Mammit ', 'Mizoram', '0389-2567335');
INSERT INTO post_office_t VALUES('Rengdil', 796441, 'Branch Office(Delivery)', 'Mamit', 'Aizawl', 'Mamit Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Rulpuihlim', 796501, 'Branch Office(Delivery)', 'Reiek', 'Aizawl', 'Reiek Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('S.Sabual', 796501, 'Branch Office(Delivery)', 'Reiek', 'Aizawl', 'Reiek Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sairang', 796410, 'Sub Office(Delivery)', '', 'Aizawl', 'Sairang Taluk of Mammit District', 'Mammit ', 'Mizoram', '0389-2568215');
INSERT INTO post_office_t VALUES('Saithah', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Serhmun', 796441, 'Branch Office(Delivery)', 'Mamit', 'Aizawl', 'West Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Silsury', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tlangkhang', 796441, 'Branch Office(Delivery)', 'Mamit', 'Aizawl', 'West Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuidam', 796441, 'Branch Office(Delivery)', 'Mamit', 'Aizawl', 'Mamit Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuipuibari', 796431, 'Branch Office(Delivery)', 'Phaileng', 'Aizawl', 'Phaileng Taluk of Mammit District', 'Mammit ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bualpui ''ng''', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chakhang', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Saiha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chapui', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Saiha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chhuarlung', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Saiha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Fungkah', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Saiha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khopai', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Laki', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Latawh', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lawngban', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungbun', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Saiha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungpher ''S''', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Saiha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('New Maubawk', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Niawhtlang', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Siaha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Phura', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Rawmibawk', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Saiha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Saiha', 796901, 'Sub Office(Delivery)', '', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '03835-226200');
INSERT INTO post_office_t VALUES('Serkawr', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Siata', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Siaha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Theiva', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tongkolong', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuipang', 796911, 'Sub Office(Delivery)', '', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '03835-280023');
INSERT INTO post_office_t VALUES('Tuipuiferry', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Saiha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tuisih', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vahai', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Vawmbuk', 796901, 'Branch Office(Delivery)', 'Saiha', 'Aizawl', 'Saiha Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zawngling', 796911, 'Branch Office(Delivery)', 'Tuipang', 'Aizawl', 'Tuipang Taluk of Saiha District', 'Saiha ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Bungtlang ''N''', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chekawn', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chhiahtlang', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Chhipphir', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Kanghmun ''S''', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Keitum', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Khawlailung', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Leng', 796370, 'Branch Office(Delivery)', 'Lungdar', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungchhuan', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungdar', 796370, 'Sub Office(Delivery)', '', 'Aizawl', 'Lungdar Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '03831-262432');
INSERT INTO post_office_t VALUES('Lungkawlh', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Lungpho', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('N.Vanlaiphai', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('New Serchhip', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sailulak', 796370, 'Branch Office(Delivery)', 'Lungdar', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Serchhip', 796181, 'Sub Office(Delivery)', '', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '03838-222019');
INSERT INTO post_office_t VALUES('Sialhau', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sialhawk', 796370, 'Branch Office(Delivery)', 'Lungdar', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Sialsir', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Thenzawl', 796186, 'Sub Office(Delivery)', '', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '-');
INSERT INTO post_office_t VALUES('Thinglian', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Tlangpui', 796370, 'Branch Office(Delivery)', 'Lungdar', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
INSERT INTO post_office_t VALUES('Zote ''S''', 796181, 'Branch Office(Delivery)', 'Serchhip', 'Aizawl', 'Serchhip Taluk of Serchhip District', 'Serchhip ', 'Mizoram', '');
