INSERT INTO rto_t VALUES(21, 'MH-01', 'Mumbai (South) – RTO is located in Tardeo');
INSERT INTO rto_t VALUES(21, 'MH-02', 'Mumbai (West) – RTO is located in Andheri');
INSERT INTO rto_t VALUES(21, 'MH-03', 'Mumbai (East) – RTO is located in Wadala');
INSERT INTO rto_t VALUES(21, 'MH-04', 'Thane');
INSERT INTO rto_t VALUES(21, 'MH-05', 'Kalyan-Dombivali, Ulhasnagar, Ambernath and Badlapur – RTO is located in Kalyan');
INSERT INTO rto_t VALUES(21, 'MH-06', 'Raigad – RTO is located in Pen (does not include Navi Mumbai, Kharghar, Panvel, Khopoli)');
INSERT INTO rto_t VALUES(21, 'MH-07', 'Sindhudurg – RTO is located in Sindhudurg Nagari');
INSERT INTO rto_t VALUES(21, 'MH-08', 'Ratnagiri');
INSERT INTO rto_t VALUES(21, 'MH-09', 'Kolhapur');
INSERT INTO rto_t VALUES(21, 'MH-10', 'Sangli');
INSERT INTO rto_t VALUES(21, 'MH-11', 'Satara');
INSERT INTO rto_t VALUES(21, 'MH-12', 'Pune (city)');
INSERT INTO rto_t VALUES(21, 'MH-13', 'Solapur (city)');
INSERT INTO rto_t VALUES(21, 'MH-14', 'Pimpri-Chinchwad');
INSERT INTO rto_t VALUES(21, 'MH-15', 'Nashik (city)');
INSERT INTO rto_t VALUES(21, 'MH-16', 'Ahmednagar');
INSERT INTO rto_t VALUES(21, 'MH-17', 'Shrirampur, Ahmednagar District');
INSERT INTO rto_t VALUES(21, 'MH-18', 'Dhule');
INSERT INTO rto_t VALUES(21, 'MH-19', 'Jalgaon');
INSERT INTO rto_t VALUES(21, 'MH-20', 'Aurangabad – RTO is located on Station Road');
INSERT INTO rto_t VALUES(21, 'MH-21', 'Jalna (city)');
INSERT INTO rto_t VALUES(21, 'MH-22', 'Parbhani');
INSERT INTO rto_t VALUES(21, 'MH-23', 'Beed');
INSERT INTO rto_t VALUES(21, 'MH-24', 'Latur');
INSERT INTO rto_t VALUES(21, 'MH-25', 'Osmanabad');
INSERT INTO rto_t VALUES(21, 'MH-26', 'Nanded');
INSERT INTO rto_t VALUES(21, 'MH-27', 'Amravati');
INSERT INTO rto_t VALUES(21, 'MH-28', 'Buldhana');
INSERT INTO rto_t VALUES(21, 'MH-29', 'Yavatmal – RTO is located on Nagpur Road');
INSERT INTO rto_t VALUES(21, 'MH-30', 'Akola – RTO is located on Murtizapur Road');
INSERT INTO rto_t VALUES(21, 'MH-31', 'Nagpur West - RTO is Located at Amravati Road');
INSERT INTO rto_t VALUES(21, 'MH-32', 'Wardha');
INSERT INTO rto_t VALUES(21, 'MH-33', 'Gadchiroli');
INSERT INTO rto_t VALUES(21, 'MH-34', 'Chandrapur');
INSERT INTO rto_t VALUES(21, 'MH-35', 'Gondia');
INSERT INTO rto_t VALUES(21, 'MH-36', 'Bhandara');
INSERT INTO rto_t VALUES(21, 'MH-37', 'Washim');
INSERT INTO rto_t VALUES(21, 'MH-38', 'Hingoli');
INSERT INTO rto_t VALUES(21, 'MH-39', 'Nandurbar');
INSERT INTO rto_t VALUES(21, 'MH-40', 'Nagpur (Rural)');
INSERT INTO rto_t VALUES(21, 'MH-41', 'Malegaon, Nashik District');
INSERT INTO rto_t VALUES(21, 'MH-42', 'Baramati, Pune');
INSERT INTO rto_t VALUES(21, 'MH-43', 'Navi Mumbai – RTO at Vashi');
INSERT INTO rto_t VALUES(21, 'MH-44', 'Ambejogai, Beed');
INSERT INTO rto_t VALUES(21, 'MH-45', 'Akluj, Solapur');
INSERT INTO rto_t VALUES(21, 'MH-46', 'Panvel-Khopoli; also MSRTC buses are registered here');
INSERT INTO rto_t VALUES(21, 'MH-47', 'Mumbai (North) – RTO is located in Kandarpada, Dahisar');
INSERT INTO rto_t VALUES(21, 'MH-48', 'Vasai-Virar / Boisar / Palghar / Dahanu');
INSERT INTO rto_t VALUES(21, 'MH-49', 'Nagpur East – RTO is located on Bhandara Road');
INSERT INTO rto_t VALUES(21, 'MH-50', 'Karad (Karad Rural) – RTO is located in Karad');
INSERT INTO rto_t VALUES(21, 'MH-51', 'Nashik (Rural)');
INSERT INTO rto_t VALUES(21, 'MH-52', 'Reserved for Parbhani (Rural)');
INSERT INTO rto_t VALUES(21, 'MH-53', 'Reserved for Pune South');
INSERT INTO rto_t VALUES(21, 'MH-54', 'Reserved for Pune North');
